# Reinhardt+ 2022 의 공개 공존선 데이터에서 engine/ice_melt_table.py 를 생성한다. 개발 전용, 런타임 아님
"""Generate `engine/ice_melt_table.py` from the published data of Reinhardt+ 2022.

    git clone https://github.com/BingqingCheng/highP-ice <dir>
    python3 engine/tools/make_ice_melt_table.py <dir>

**This script is not a runtime dependency.** It reads the data repository once and writes a
plain-Python module with no imports — the same discipline as `make_water_table.py` and
`make_hhe_table.py`: the source is read at build time and checked at test time, never by
`scripts/check.sh`. The data are transcribed by this script, never by hand.

The source is Reinhardt, Bethkenhagen, Coppari, Millot, Hamel & Cheng 2022, *Thermodynamics
of high-pressure ice phases explored with atomistic simulations*, Nat Commun 13, 4707
(2022NatCo..13.4707R, arXiv:2203.12897). Its `figs-1-and-S1/README.txt` says the
`coex-*.dat` files "contain coexistence points computed from thermodynamic integration or
direct coexistence, as indicated" — the blue line (liquid–solid), the brown line
(ice VII′–VII″) and the red triangles (direct coexistence) of Fig. 1a.

Two lines are baked, one benchmark set is kept for the test:

- `LIQUID_LINE`: the liquid–solid coexistence, thermodynamic integration, 10–52.4 GPa.
  The recipe uses it above IAPWS equation (5)'s end (20.6 GPa); the low end is kept so the
  seam can be measured against IAPWS where the two overlap.
- `VII1_VII2_LINE`: the ice VII′–VII″ coexistence, thermodynamic integration along isobars,
  20–70 GPa. First order by the chemical-potential slope (paper, Fig. 1e).
- `DIRECT_COEXISTENCE`: the paper's own benchmark of the liquid line, six points. Not used
  by the recipe; the test checks the baked line against them.

`discontinuity-kink.dat` (the cyan dashed line, brute-force density/enthalpy jumps) is not
baked: the paper describes it as the cruder view of the same transition the brown line
locates thermodynamically.
"""
import os
import subprocess
import sys

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "ice_melt_table.py")
FILES = {
    "LIQUID_LINE": "figs-1-and-S1/coex-line-liquid.dat",
    "VII1_VII2_LINE": "figs-1-and-S1/coex-line-superionic-ice.dat",
    "DIRECT_COEXISTENCE": "figs-1-and-S1/coex-direct-coexistence.dat",
}
# 논문 본문이 적는 삼중점 (§IV: "a triple point between the liquid, VII′ and VII″ at
# ∼20 GPa and 875 K"). 굳힌 데이터가 이 점을 지나는지를 생성 시점에 확인한다.
TRIPLE_POINT = (20.0, 875.0)


def read_points(path):
    """`#P/GPa T/K` 파일. 별표(*) 는 직접 공존으로 검증된 점의 표시이고 값이 아니다."""
    out = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.replace("*", " ").split()
            p_gpa, t_k = float(parts[0]), float(parts[1])
            out.append((p_gpa, t_k, "*" in line))
    if any(out[i][0] >= out[i + 1][0] for i in range(len(out) - 1)):
        raise SystemExit(f"{path}: pressures are not strictly increasing")
    return out


def data_commit(root):
    try:
        return subprocess.check_output(["git", "-C", root, "rev-parse", "HEAD"],
                                       text=True).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def main(root):
    tables = {name: read_points(os.path.join(root, rel)) for name, rel in FILES.items()}
    liquid = tables["LIQUID_LINE"]
    tp = [pt for pt in liquid if pt[0] == TRIPLE_POINT[0]]
    if not tp or tp[0][1] != TRIPLE_POINT[1]:
        raise SystemExit(f"liquid line does not pass through the paper's triple point "
                         f"{TRIPLE_POINT}: {tp}")
    commit = data_commit(root)
    lines = [
        "# Reinhardt+ 2022 의 물 액체–고체 공존선과 얼음 VII′–VII″ 공존선 — 생성된 파일이다. 손으로 고치지 말 것",
        '"""Baked coexistence lines of high-pressure water, Reinhardt+ 2022.',
        "",
        "**Generated by `engine/tools/make_ice_melt_table.py`; do not edit by hand.** The source",
        "is the data repository of Reinhardt, Bethkenhagen, Coppari, Millot, Hamel & Cheng 2022,",
        "*Thermodynamics of high-pressure ice phases explored with atomistic simulations*,",
        "Nat Commun 13, 4707 (2022NatCo..13.4707R, arXiv:2203.12897):",
        f"https://github.com/BingqingCheng/highP-ice at commit {commit}.",
        "",
        "Points are (P [GPa], T [K]) as published, in the order published. The third field of",
        "the liquid line marks the points the paper starred as benchmarked by direct coexistence.",
        "Machine-learned potential fitted to PBE DFT — a simulation, not a measurement. The",
        "consumer (`eos.py`) interpolates linearly between points and grades the answer analog.",
        '"""',
        "",
    ]
    for name, rel in FILES.items():
        pts = tables[name]
        lines.append(f"# {rel}")
        lines.append(f"{name} = (")
        for p_gpa, t_k, starred in pts:
            if name == "LIQUID_LINE":
                lines.append(f"    ({p_gpa!r}, {t_k!r}, {starred}),")
            else:
                lines.append(f"    ({p_gpa!r}, {t_k!r}),")
        lines.append(")")
        lines.append("")
    lines.append(f"DATA_COMMIT = {commit!r}")
    lines.append(f"TRIPLE_POINT_GPA_K = {TRIPLE_POINT!r}   # 논문 §IV 의 액체–VII′–VII″ 삼중점")
    lines.append("")
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    n = {k: len(v) for k, v in tables.items()}
    print(f"wrote {OUT}: {n}, data commit {commit[:12]}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
