# SeaFreeze water1 (Bollengier+ 2019) 에서 engine/water_table.py 를 생성한다. 개발 venv 전용, 런타임 아님
"""Generate `engine/water_table.py` from SeaFreeze's `water1` liquid-water representation.

    engine/.venv/bin/python engine/tools/make_water_table.py

**This script is not a runtime dependency.** It runs once in the development venv (the one
that has SeaFreeze), and its output is a plain-Python module with no imports — the same
discipline as `make_hhe_table.py` and as the ice III/V/VI constants: SeaFreeze is read at
build time and checked at test time, never imported by `scripts/check.sh`.

`water1` is Bollengier, Brown & Shaw 2019 (2019JChPh.151e4501B), the Gibbs-energy local
basis function representation SeaFreeze ships for pure liquid water: sound speeds measured
to 700 MPa down to the freezing point, and an equation of state fitted to 2300 MPa over
240–500 K. That window is the ocean under an ice shell, up to and slightly past the
ice VI → VII transition (2.216 GPa), which is where the IAPWS melting curve this recipe
carries runs out of low-pressure branches.

**Why a table and not three constants.** Ices III·V·VI went in as (ρ₀, K₀, K₀′) read at one
reference state plus (αK_T, c_V), and reproduce SeaFreeze to 0.006–0.118 %. The same
reading of `water1` is 5.3 % off at 2.2 GPa on the 273 K isotherm and 10.6 % at 400 K,
because αK_T of liquid water changes sign at the density maximum (277 K) and grows
forty-fold across the window — the "αK_T independent of volume" approximation the closed
forms rest on does not hold for a liquid here. Measured in
`engine/ocean-layer-context-notes.md` before this route was chosen.

Two quantities are kept on a regular (P, T) grid: ρ [kg/m³] and the adiabatic slope
dT/dP|_S = α T / (ρ c_P) [K/Pa]. The second is why the ocean has a temperature gradient at
all — the integrator carries T along dT = (dT/dP) dP through this layer as it does through
the H/He envelope, reading a published slope rather than assembling one.
"""
import os
import sys

import numpy as np

# 굳히는 창. water1 의 매듭 구간 전체(0–2300 MPa · 239–501 K)에서 격자점이 매듭 안에
# 들어오도록 안쪽에서 잡는다. 25 MPa · 4 K 에서 아래 self-check 가 재는 보간 오차는
# 얼음 껍질 아래 바다가 놓이는 252–360 K 에서 밀도 2e-4 안이고, 창 전체의 최악은 저압·
# 고온 모서리(증기압 곡선 근처, 압축률이 큰 자리)에서 6e-4 다 — 바다가 없는 자리다.
P_LO_MPA, P_HI_MPA, P_STEP_MPA = 0.0, 2300.0, 25.0
T_LO_K, T_HI_K, T_STEP_K = 240.0, 500.0, 4.0


def grid():
    ps = np.arange(P_LO_MPA, P_HI_MPA + 0.5 * P_STEP_MPA, P_STEP_MPA)
    ts = np.arange(T_LO_K, T_HI_K + 0.5 * T_STEP_K, T_STEP_K)
    return ps, ts


def evaluate(ps_mpa, ts_k):
    from seafreeze.seafreeze import getProp
    pt = np.empty((len(ps_mpa) * len(ts_k),), dtype=object)
    k = 0
    for t in ts_k:
        for p in ps_mpa:
            pt[k] = (float(p), float(t))
            k += 1
    out = getProp(pt, "water1")
    rho = np.asarray(out.rho, dtype=float).reshape(len(ts_k), len(ps_mpa))
    alpha = np.asarray(out.alpha, dtype=float).reshape(len(ts_k), len(ps_mpa))
    cp = np.asarray(out.Cp, dtype=float).reshape(len(ts_k), len(ps_mpa))
    tt = np.asarray(ts_k, dtype=float)[:, None]
    dtdp = alpha * tt / (rho * cp)          # K/Pa
    return rho, dtdp


def fmt_row(vals, digits):
    return "(" + ",".join(f"{v:.{digits}e}" for v in vals) + "),"


def main():
    ps, ts = grid()
    rho, dtdp = evaluate(ps, ts)
    here = os.path.dirname(os.path.abspath(__file__))
    target = os.path.join(here, "..", "water_table.py")
    lines = [
        "# SeaFreeze water1 (Bollengier+ 2019) 의 액체 물 상태방정식 표 — 생성된 파일이다. 손으로 고치지 말 것",
        '"""Baked liquid-water equation of state, Bollengier, Brown & Shaw 2019.',
        "",
        "**Generated by `engine/tools/make_water_table.py`; do not edit by hand.** The source is",
        "SeaFreeze v1.1.0's `water1` spline (Journaux+ 2020, 2020JGRE..12506176J), whose README",
        "attributes it to Bollengier, Brown & Shaw 2019 (2019JChPh.151e4501B): an equation of",
        "state for pure liquid water to 2300 MPa over 240-500 K, anchored on sound speeds",
        "measured to 700 MPa down to the freezing point.",
        "",
        "Two quantities are kept on a regular (P, T) grid: rho [kg/m^3] and the adiabatic slope",
        "dT/dP|_S = alpha T / (rho c_P) [K/Pa]. Bilinear interpolation; the interpolation error",
        "measured against the spline at off-grid points is recorded below by the generator.",
        '"""',
        "",
        f"P_LO_PA = {P_LO_MPA * 1e6!r}",
        f"P_STEP_PA = {P_STEP_MPA * 1e6!r}",
        f"NP = {len(ps)}",
        f"T_LO_K = {T_LO_K!r}",
        f"T_STEP_K = {T_STEP_K!r}",
        f"NT = {len(ts)}",
        "",
        "# rho [kg/m^3]. 바깥 튜플이 등온선(T = T_LO_K + i*T_STEP_K), 안쪽이 압력.",
        "RHO = (",
    ]
    for i in range(len(ts)):
        lines.append("    " + fmt_row(rho[i], 7))
    lines.append(")")
    lines.append("")
    lines.append("# dT/dP|_S [K/Pa]. 같은 격자.")
    lines.append("DTDP_S = (")
    for i in range(len(ts)):
        lines.append("    " + fmt_row(dtdp[i], 6))
    lines.append(")")
    lines.append("")
    lines.append(TAIL)
    open(target, "w").write("\n".join(lines) + "\n")

    # 자기 검사: 격자 사이 점에서 스플라인과 보간의 차이. 두 줄로 잰다 — 바다가 실제로
    # 놓이는 구간(녹는곡선의 최저점 251 K 위)과 창 전체. 창의 아래 모서리(240–250 K,
    # 저압)는 과냉각 물이라 곡률이 크고, 거기가 창 전체의 최악을 정한다.
    sys.path.insert(0, os.path.join(here, ".."))
    import importlib
    wt = importlib.import_module("water_table")
    importlib.reload(wt)
    from seafreeze.seafreeze import getProp
    print(f"wrote {target}: {len(ts)} x {len(ps)} grid")
    for label, t_lo, t_hi in (("252-360 K (under an ice shell)", 252.0, 360.0),
                              ("whole window", 242.0, 499.0)):
        worst_r, worst_s = 0.0, 0.0
        for p in np.arange(12.5, 2290.0, 62.5):
            for t in np.arange(t_lo, t_hi, 6.0):
                pt = np.empty((1,), dtype=object)
                pt[0] = (float(p), float(t))
                o = getProp(pt, "water1")
                r_sf = float(o.rho[0])
                s_sf = float(o.alpha[0]) * t / (r_sf * float(o.Cp[0]))
                worst_r = max(worst_r, abs(wt.density(p * 1e6, t) / r_sf - 1.0))
                worst_s = max(worst_s, abs(wt.dtdp_adiabat(p * 1e6, t) - s_sf))
        print(f"  {label}: rho {worst_r:.2e} (relative), dT/dP {worst_s * 1e9:.2e} K/GPa (absolute)")

TAIL = '''
# 굳힌 창의 경계. 표는 양 끝을 포함한다.
P_MAX_PA = P_LO_PA + (NP - 1) * P_STEP_PA
T_MAX_K = T_LO_K + (NT - 1) * T_STEP_K


def in_domain(p_pa, t_k):
    return P_LO_PA <= p_pa <= P_MAX_PA and T_LO_K <= t_k <= T_MAX_K


def _cell(p_pa, t_k):
    fp = (p_pa - P_LO_PA) / P_STEP_PA
    ft = (t_k - T_LO_K) / T_STEP_K
    i = min(max(int(ft), 0), NT - 2)
    j = min(max(int(fp), 0), NP - 2)
    return i, j, ft - i, fp - j


def _bilinear(table, p_pa, t_k):
    i, j, u, v = _cell(p_pa, t_k)
    r0, r1 = table[i], table[i + 1]
    return ((1.0 - u) * ((1.0 - v) * r0[j] + v * r0[j + 1])
            + u * ((1.0 - v) * r1[j] + v * r1[j + 1]))


def density(p_pa, t_k):
    """rho [kg/m^3]. 창 밖은 부르는 쪽이 먼저 막는다 (in_domain)."""
    return _bilinear(RHO, p_pa, t_k)


def dtdp_adiabat(p_pa, t_k):
    """dT/dP|_S [K/Pa] — the published alpha T / (rho c_P), interpolated."""
    return _bilinear(DTDP_S, p_pa, t_k)
'''


if __name__ == "__main__":
    main()
