# SeaFreeze water2 (Brown 2018) 에서 engine/water2_table.py 를 생성한다 — 2.3 GPa 위·500–1000 K 의 조밀한 액체 물. 개발 venv 전용, 런타임 아님
"""Generate `engine/water2_table.py` from SeaFreeze's `water2` liquid-water representation.

    engine/.venv/bin/python engine/tools/make_water2_table.py

**Not a runtime dependency** — the same discipline as `make_water_table.py`: SeaFreeze is read
once here, the output is a plain-Python module with no imports beyond `math`, and
`scripts/check.sh` runs on system Python.

`water2` is Brown 2018 (2018FlPEq.463...18B, *Local basis function representations of
thermodynamic surfaces: H₂O at high pressure and temperature as an example*, Fluid Phase
Equilibria 463, 18), the Gibbs-energy local-basis-function representation SeaFreeze ships
for dense liquid and supercritical water. Its spline knots run 0–100 000 MPa × 240–10 000 K
(read from `splines/water_Brown/water_Brown.mat` with h5py). Brown's own paper is paywalled
with no preprint and its fit-and-residual discussion has not been read here; the readable
third-party statement of its range is AQUA, Haldemann+ 2020 §2.3.5 (2020A&A...643A.105H,
arXiv 2009.10098, in the cache): "Brown (2018) provide an EoS which is appropriate for
liquid and supercritical H₂O from 1 GPa to 100 GPa and up to 10⁴ K" — and AQUA uses it as its
region 5, the very band this table is baked for.

**What this table is for.** The band this recipe had no equation of state in: liquid water
above the ocean table's 2.3 GPa (or above its 500 K) and below the hot-water fit's 1000 K
floor (Mazevet+ 2019 §3.1, ρ ≳ 1 g/cc). `eos.py` threw *too cold* there and the shooting
loop pushed the central temperature up — F2's Callisto and Titan at f = 0.75 ran past 70
CPU-minutes on exactly that. So the grid covers 0.1–100 GPa × 240–1100 K: the top edge is
100 K past the Mazevet floor so the seam can be measured from inside, the low-pressure edge
is where supercritical water below 0.1 GPa is steam-like and a bilinear grid stops being
honest (that corner is declined by name, not baked). The 10 000 K the knots allow is not
baked: above 1000 K the hot-water fit already carries the liquid and the ice giants' anchors
stand on it.

Three quantities on a regular (log₁₀ P, T) grid: ρ [kg/m³], the adiabatic slope
dT/dP|_S = α T / (ρ c_P) [K/Pa], and c_P [J/kg/K] — the third so a rock-bearing mixture in
this band can weight ∇_ad by c_P the way `Mixture.grad_ad` requires (the ocean table lacks
it, which is why rock is only mixed above 2.3 GPa).

**Two seams, measured here and written into the module.** water1 ↔ water2 inside their
overlap (0.1–2.3 GPa × 240–500 K; both are SeaFreeze, so a disagreement is a finding about
the library), and — in `test_water2.py`, which has the hot-water fit — water2 ↔ Mazevet+
2019 along 1000 K.
"""
import os
import sys

import numpy as np

# 격자. log10 P [GPa] 균일 (0.1–100 GPa), T 균일 (240–1100 K). 쌍선형 보간.
LOGP_LO, LOGP_HI, LOGP_STEP = -1.0, 2.0, 0.02
T_LO_K, T_HI_K, T_STEP_K = 360.0, 1100.0, 10.0
# 360 K 아래는 굳히지 않는다: 이 표가 불리는 자리는 2.3 GPa 위(그 압력의 녹는점이 362 K) 아니면
# 500 K 위이고, 그 아래는 water1 의 자리다. 게다가 스플라인이 240–350 K 에서 0.1–2 GPa 부터
# 비물리적이라(2026-08-30 측정, 아래 이음매 검사가 그 수를 든다) 굳힐 것이 없다.
# 물리적인 액체 물의 c_P 창 [J/kg/K]. 스플라인이 이 밖의 값을 내면 그 자리는 유효하지 않다.
CP_MIN, CP_MAX = 1000.0, 15000.0


def grid():
    lps = np.round(np.arange(LOGP_LO, LOGP_HI + 0.5 * LOGP_STEP, LOGP_STEP), 6)
    ts = np.arange(T_LO_K, T_HI_K + 0.5 * T_STEP_K, T_STEP_K)
    return lps, ts


def props(key, p_mpa, t_k):
    from seafreeze.seafreeze import getProp
    pt = np.empty((len(p_mpa) * len(t_k),), dtype=object)
    k = 0
    for t in t_k:
        for p in p_mpa:
            pt[k] = (float(p), float(t))
            k += 1
    out = getProp(pt, key)
    shape = (len(t_k), len(p_mpa))
    rho = np.asarray(out.rho, dtype=float).reshape(shape)
    alpha = np.asarray(out.alpha, dtype=float).reshape(shape)
    cp = np.asarray(out.Cp, dtype=float).reshape(shape)
    tt = np.asarray(t_k, dtype=float)[:, None]
    return rho, alpha * tt / (rho * cp), cp


def fmt_row(vals, digits):
    return "(" + ",".join(f"{v:.{digits}e}" for v in vals) + "),"


HEAD = '''# SeaFreeze water2 (Brown 2018) 의 조밀한 액체 물 상태방정식 표 — 생성된 파일이다. 손으로 고치지 말 것
"""Baked dense-liquid-water equation of state, Brown 2018 (SeaFreeze `water2`).

**Generated by `engine/tools/make_water2_table.py`; do not edit by hand.** The source is
SeaFreeze v1.1.0's `water2` spline (Journaux+ 2020, 2020JGRE..12506176J), which the README
attributes to Brown 2018 (2018FlPEq.463...18B): a Gibbs-energy local-basis-function
representation of liquid and supercritical water whose knots run 0-100 GPa and 240-10 000 K.
Its range as a third party states it: "appropriate for liquid and supercritical H2O from
1 GPa to 100 GPa and up to 10^4 K" (AQUA, Haldemann+ 2020 sec. 2.3.5, 2020A&A...643A.105H).

Baked window: 0.1 GPa up to a ragged ceiling (KEEP, below) x 360-1100 K. Three quantities:
rho [kg/m^3], the adiabatic slope dT/dP|_S [K/Pa], and c_P [J/kg/K]. Bilinear in
(log10 P, T). **The ceiling is the spline's, not the knots'**: SeaFreeze's water2 returns
negative densities and c_P of 10^6 J/kg/K well inside its 100 GPa knot box (about 15 GPa at
700 K, 36 GPa at 1000 K), so each isotherm is baked only up to two cells before the first
unphysical value. Interpolation error and the water1 <-> water2 seam are measured by the
generator and recorded below.
"""

import math

LOGP_LO = {LOGP_LO!r}
LOGP_STEP = {LOGP_STEP!r}
NP = {NP}
T_LO_K = {T_LO_K!r}
T_STEP_K = {T_STEP_K!r}
NT = {NT}
'''

TAIL = '''
# 굳힌 창의 경계. 표는 양 끝을 포함한다.
P_MIN_PA = 10.0 ** LOGP_LO * 1e9
P_MAX_PA = 10.0 ** (LOGP_LO + (max(KEEP) - 1) * LOGP_STEP) * 1e9   # 가장 뜨거운 등온선의 천장
T_MAX_K = T_LO_K + (NT - 1) * T_STEP_K


def p_ceiling(t_k):
    """이 온도에서 표가 유효한 압력 천장 [Pa] — 감싸는 두 등온선 중 낮은 쪽."""
    i = min(max(int((t_k - T_LO_K) / T_STEP_K), 0), NT - 2)
    n = min(KEEP[i], KEEP[i + 1])
    return 10.0 ** (LOGP_LO + (n - 1) * LOGP_STEP) * 1e9


def in_domain(p_pa, t_k):
    if not (T_LO_K <= t_k <= T_MAX_K):
        return False
    return P_MIN_PA <= p_pa <= p_ceiling(t_k) * (1.0 + 1e-12)


def _cell(p_pa, t_k):
    fp = (math.log10(p_pa / 1e9) - LOGP_LO) / LOGP_STEP
    ft = (t_k - T_LO_K) / T_STEP_K
    i = min(max(int(ft), 0), NT - 2)
    j = min(max(int(fp), 0), NP - 2)
    return i, j, ft - i, fp - j


def _bilinear(table, p_pa, t_k):
    i, j, u, v = _cell(p_pa, t_k)
    r0, r1 = table[i], table[i + 1]
    return ((1.0 - u) * ((1.0 - v) * r0[j] + v * r0[j + 1])
            + u * ((1.0 - v) * r1[j] + v * r1[j + 1]))


def density(p_pa, t_k):
    """rho [kg/m^3]. 창 밖은 부르는 쪽이 먼저 막는다 (in_domain)."""
    return _bilinear(RHO, p_pa, t_k)


def dtdp_adiabat(p_pa, t_k):
    """dT/dP|_S [K/Pa]. 표가 든 값이지 조립한 것이 아니다."""
    return _bilinear(DTDP_S, p_pa, t_k)


def c_p(p_pa, t_k):
    """c_P [J/kg/K]. 혼합의 grad_ad 가중치."""
    return _bilinear(C_P, p_pa, t_k)
'''


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    target = os.path.join(here, "..", "water2_table.py")
    lps, ts = grid()
    p_mpa = 10.0 ** lps * 1e3
    rho, dtdp, cp = props("water2", p_mpa, ts)

    # ── 스플라인이 실제로 유효한 자리만 굳힌다 (들쭉날쭉한 천장) ──
    # 매듭 상자는 0–100 GPa 인데, 스플라인은 그 안쪽에서 비물리적으로 간다 — 700 K 에서 ~15 GPa
    # 위는 밀도가 음수, c_P 가 10⁶ 이 된다 (2026-08-30 측정; 라이브러리에 대한 발견이고 우리 것이
    # 아니다). 등온선마다 처음 어긋나는 칸의 두 칸 앞까지만 굳히고 그 위는 이름 대며 거절한다.
    keep = []
    for i in range(len(ts)):
        r, c, d = rho[i], cp[i], dtdp[i]
        ok = np.isfinite(r) & (r > 0) & np.isfinite(c) & (c > CP_MIN) & (c < CP_MAX) & np.isfinite(d) & (d > 0)
        mono = np.concatenate([[True], np.diff(r) > 0])
        # 압축률의 폭주: 연속 증분의 비가 3 을 넘으면 그 앞에서 자른다
        inc = np.diff(r)
        calm = np.concatenate([[True, True], (inc[1:] < 3.0 * np.maximum(inc[:-1], 1e-9))])
        good = ok & mono & calm
        n = int(np.argmin(good)) if not good.all() else len(good)
        keep.append(max(n - 2, 2))
    keep = np.array(keep)
    assert keep.min() >= 4, f"too few valid cells on some isotherm: {keep.min()}"
    # 천장 너머는 검사 스텐실에도 들어오지 않게 지운다 — 굳히지 않는 값이 검사 수를 오염시키면 안 된다.
    for i in range(len(ts)):
        rho[i, keep[i]:] = np.nan
        dtdp[i, keep[i]:] = np.nan
        cp[i, keep[i]:] = np.nan

    # ── 자기 검사 1: 격자 사이 보간 오차 (창 전체와, 이 표가 실제로 받는 띠) ──
    def interp(table, p_pa, t):
        fp = (np.log10(p_pa / 1e9) - LOGP_LO) / LOGP_STEP
        ft = (t - T_LO_K) / T_STEP_K
        i = int(min(max(ft, 0), len(ts) - 2)); j = int(min(max(fp, 0), len(lps) - 2))
        u, v = ft - i, fp - j
        r0, r1 = table[i], table[i + 1]
        return ((1 - u) * ((1 - v) * r0[j] + v * r0[j + 1]) + u * ((1 - v) * r1[j] + v * r1[j + 1]))

    def ceiling_logp(t):
        i = int(min(max((t - T_LO_K) / T_STEP_K, 0), len(ts) - 2))
        return lps[min(keep[i], keep[i + 1]) - 1]

    checks = {}
    for label, lp_lo, lp_hi, t_lo, t_hi in (("band 2.3-10 GPa x 500-1000 K", np.log10(2.3), 1.0, 500.0, 1000.0),
                                            ("whole window", LOGP_LO + 0.005, LOGP_HI - 0.005, T_LO_K + 2.0, T_HI_K - 2.0)):
        lp_s = np.arange(lp_lo + 0.01, lp_hi, 0.05)
        t_s = np.arange(t_lo + 5.0, t_hi, 25.0)
        rho_s, dtdp_s, cp_s = props("water2", 10.0 ** lp_s * 1e3, t_s)
        worst = [0.0, 0.0, 0.0]
        for a, t in enumerate(t_s):
            for b, lp in enumerate(lp_s):
                if lp > ceiling_logp(t) - 2.5 * LOGP_STEP:
                    continue        # 들쭉날쭉한 천장의 두 칸 안은 이웃 등온선이 짧아 스텐실이 잘린다
                p_pa = 10.0 ** lp * 1e9
                e = (abs(interp(rho, p_pa, t) / rho_s[a, b] - 1.0),
                     abs(interp(dtdp, p_pa, t) - dtdp_s[a, b]) / abs(dtdp_s[a, b]),
                     abs(interp(cp, p_pa, t) / cp_s[a, b] - 1.0))
                if not all(np.isfinite(e)):
                    continue            # 스텐실이 천장 너머를 밟았다 — 그 자리는 표 밖이다
                worst = [max(w, x) for w, x in zip(worst, e)]
        checks[label] = worst

    # ── 자기 검사 2: water1 ↔ water2 이음매, 겹침 구간 (0.1-2.3 GPa x 240-500 K), 둘 다 스플라인에서 직접 ──
    lp_o = np.arange(LOGP_LO, np.log10(2.3), 0.05)
    t_o = np.arange(240.0, 500.0, 10.0)
    r1, d1, c1 = props("water1", 10.0 ** lp_o * 1e3, t_o)
    r2, d2, c2 = props("water2", 10.0 ** lp_o * 1e3, t_o)
    seam_rho = np.abs(r2 / r1 - 1.0)
    seam_dtdp = np.abs(d2 - d1) / np.abs(d1)
    seam_cp = np.abs(c2 / c1 - 1.0)
    for arr in (seam_rho, seam_dtdp, seam_cp):
        arr[~np.isfinite(arr)] = np.inf
    ia = np.unravel_index(np.argmax(seam_rho), seam_rho.shape)
    ib = np.unravel_index(np.argmax(seam_dtdp), seam_dtdp.shape)
    ic = np.unravel_index(np.argmax(seam_cp), seam_cp.shape)
    # 바다가 실제로 놓이는 자리 (252-360 K) 와, 이 표가 굳힌 온도 (360-500 K) 를 따로.
    sel = (t_o >= 252.0) & (t_o <= 360.0)
    seam_rho_ocean = float(np.max(seam_rho[sel]))
    seam_dtdp_ocean = float(np.max(seam_dtdp[sel]))
    selb = t_o >= T_LO_K
    seam_rho_baked = float(np.max(seam_rho[selb]))
    seam_dtdp_baked = float(np.max(seam_dtdp[selb]))
    seam_cp_baked = float(np.max(seam_cp[selb]))
    # 겹침의 어디서부터 water2 가 water1 과 1 % 안에서 맞는가 (등온선별 최저 온도)

    lines = [HEAD.format(LOGP_LO=LOGP_LO, LOGP_STEP=LOGP_STEP, NP=len(lps), T_LO_K=T_LO_K,
                         T_STEP_K=T_STEP_K, NT=len(ts))]
    lines.append("# 등온선마다 굳힌 열의 개수. 그 위는 스플라인이 비물리적이라(밀도 음수·c_P 폭주) 굳히지")
    lines.append("# 않았고 이름 대며 거절한다 — 매듭 상자(100 GPa)가 아니라 실제 유효 천장이다. 생성기가 잰다.")
    lines.append("KEEP = (" + ",".join(str(int(k)) for k in keep) + ")")
    lines.append("")
    lines.append("# rho [kg/m^3]. 바깥 튜플이 등온선(T = T_LO_K + i*T_STEP_K), 안쪽이 log10 P (KEEP 만큼).")
    lines.append("RHO = (")
    for i in range(len(ts)):
        lines.append("    " + fmt_row(rho[i][:keep[i]], 7))
    lines.append(")\n")
    lines.append("# dT/dP|_S [K/Pa]. 같은 격자.")
    lines.append("DTDP_S = (")
    for i in range(len(ts)):
        lines.append("    " + fmt_row(dtdp[i][:keep[i]], 6))
    lines.append(")\n")
    lines.append("# c_P [J/kg/K]. 같은 격자.")
    lines.append("C_P = (")
    for i in range(len(ts)):
        lines.append("    " + fmt_row(cp[i][:keep[i]], 6))
    lines.append(")\n")
    lines.append("# 생성기가 잰 것. 격자 사이 점에서 스플라인과 보간의 차 (상대, 최악).")
    for label, w in checks.items():
        key = "BAND" if label.startswith("band") else "WINDOW"
        lines.append(f"INTERP_{key}_RHO = {w[0]:.2e}      # {label}")
        lines.append(f"INTERP_{key}_DTDP = {w[1]:.2e}")
        lines.append(f"INTERP_{key}_CP = {w[2]:.2e}")
    lines.append("# water1 (Bollengier+ 2019) 과 water2 (Brown 2018) 의 이음매, 겹침 구간 0.1-2.3 GPa x 240-500 K,")
    lines.append("# 둘 다 SeaFreeze 에서 직접 평가한 값의 차 (상대, 최악). 바다 자리(252-360 K)는 따로.")
    lines.append(f"SEAM_W1_RHO = {float(seam_rho.max()):.2e}       # at {10 ** lp_o[ia[1]]:.2f} GPa, {t_o[ia[0]]:.0f} K")
    lines.append(f"SEAM_W1_DTDP = {float(seam_dtdp.max()):.2e}      # at {10 ** lp_o[ib[1]]:.2f} GPa, {t_o[ib[0]]:.0f} K")
    lines.append(f"SEAM_W1_CP = {float(seam_cp.max()):.2e}        # at {10 ** lp_o[ic[1]]:.2f} GPa, {t_o[ic[0]]:.0f} K")
    lines.append(f"SEAM_W1_RHO_OCEAN = {seam_rho_ocean:.2e}      # 252-360 K, where an ocean sits (water1's job; not baked here)")
    lines.append(f"SEAM_W1_DTDP_OCEAN = {seam_dtdp_ocean:.2e}")
    lines.append(f"SEAM_W1_RHO_BAKED = {seam_rho_baked:.2e}      # 360-500 K x 0.1-2.3 GPa, the overlap this table actually carries")
    lines.append(f"SEAM_W1_DTDP_BAKED = {seam_dtdp_baked:.2e}")
    lines.append(f"SEAM_W1_CP_BAKED = {seam_cp_baked:.2e}")
    lines.append(TAIL)
    open(target, "w").write("\n".join(lines) + "\n")

    print(f"wrote {target}: {len(ts)} x {len(lps)} grid, ragged — valid ceiling by isotherm:")
    for t in (240, 300, 360, 400, 500, 600, 700, 800, 900, 1000, 1100):
        i = int((t - T_LO_K) / T_STEP_K)
        print(f"    {t:5d} K: {10 ** lps[keep[i] - 1]:7.2f} GPa ({keep[i]} cells)")
    for label, w in checks.items():
        print(f"  interpolation, {label}: rho {w[0]:.2e} · dT/dP {w[1]:.2e} · c_P {w[2]:.2e} (relative, worst)")
    print(f"  seam water1<->water2, overlap: rho {seam_rho.max():.2e} at {10 ** lp_o[ia[1]]:.2f} GPa {t_o[ia[0]]:.0f} K · "
          f"dT/dP {seam_dtdp.max():.2e} at {10 ** lp_o[ib[1]]:.2f} GPa {t_o[ib[0]]:.0f} K · c_P {seam_cp.max():.2e}")
    print(f"  seam, ocean region 252-360 K: rho {seam_rho_ocean:.2e} · dT/dP {seam_dtdp_ocean:.2e}")
    print(f"  seam, baked overlap 360-500 K: rho {seam_rho_baked:.2e} · dT/dP {seam_dtdp_baked:.2e} · c_P {seam_cp_baked:.2e}")
    # 등온선별: water2 가 water1 과 밀도 1 % 안에 드는 압력 구간
    for a, t in enumerate(t_o):
        okp = lp_o[seam_rho[a] < 0.01]
        print(f"    {t:4.0f} K: |rho2/rho1-1| < 1 % over " + (f"{10 ** okp.min():.2f}-{10 ** okp.max():.2f} GPa" if len(okp) else "nowhere")
              + f"; worst {seam_rho[a].max():.2e}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
