# Chabrier+ 2019 배포 표에서 engine/hhe_table.py 를 생성한다. 개발 venv 전용, 런타임 아님
"""Generate `engine/hhe_table.py` from the distributed Chabrier+ 2019 EOS tables.

    curl -O https://perso.ens-lyon.fr/gilles.chabrier/DirEOS/DirEOS2019.tar.gz
    tar xzf DirEOS2019.tar.gz
    engine/.venv/bin/python engine/tools/make_hhe_table.py DirTABLES-EOS2019

**This script is not a runtime dependency.** It runs once, in the development venv, and
its output is a plain-Python module with no imports. `scripts/check.sh` never calls it;
`engine/test_giant.py` re-runs it against the same distributed file when that file is
present, and prints SKIP when it is not. Same discipline as ices III/V/VI and the Fermi
integrals.
"""
import sys
import os

# 굳히는 창. 행성 외피가 실제로 지나는 구간이고, 표 전체(log P −9…13, log T 2…8)의
# 일부다. 위쪽 끝 log P = 4 는 목성 중심(약 4000 GPa) 위, log T = 4.4 는 그 중심온도
# (약 20000 K) 위다.
LOGT_LO, LOGT_HI = 2.00, 4.40
LOGP_LO, LOGP_HI = -4.00, 4.00
STEP = 0.05

# 도달 가능 영역의 아래 경계. 표 자신의 grad_ad 로 1 bar · 50 K 에서 바깥으로 적분한
# 단열선이 log T = 2.8198 + 0.2567 log P 이고, 거기서 0.10 dex 아래에 선을 긋는다.
# 50 K 는 이 리포지토리가 선언할 어떤 포텐셜 온도보다도 차다 (천왕성 1 bar 가 76 K).
# 그 아래는 대류하는 외피가 닿지 않는 자리이고, **배포 표의 결함이 전부 거기 있다.**
REACH_A, REACH_B = 2.6198 + 0.10, 0.2567

# 배포 표가 밀도 자리에 넣어 둔 값. README 가 "numerical oscillations or flaws ...
# are expected" 라고 예고한 그것이고, 우리 창 안에 7칸 있다. 전부 도달 불가 영역이다.
SENTINEL = -8.8603

PAD = 2          # 보간 스텐실이 경계에서 걸치는 만큼 여유로 더 굳힌다


def read(path):
    rows = []
    for line in open(path):
        if line.startswith("#"):
            continue
        rows.append([float(x) for x in line.split()])
    nt = len({r[0] for r in rows})
    npres = len(rows) // nt
    return [rows[i * npres:(i + 1) * npres] for i in range(nt)]


def main(root):
    src = os.path.join(root, "TABLEEOS_HHE_TP_IVL_Y0.275_v1")
    grid = read(src)
    nt = int(round((LOGT_HI - LOGT_LO) / STEP)) + 1
    npc = int(round((LOGP_HI - LOGP_LO) / STEP)) + 1
    i0 = int(round((LOGT_LO - grid[0][0][0]) / STEP))
    j0 = int(round((LOGP_LO - grid[0][0][1]) / STEP))

    rho_rows, gad_rows, cp_rows, keep_rows = [], [], [], []
    sentinels = []
    for i in range(nt):
        row = grid[i0 + i][j0:j0 + npc]
        lt = row[0][0]
        # 이 등온선에서 도달 가능한 마지막 열. logT >= A + B logP 를 logP 로 푼다.
        jmax = npc - 1
        if lt < REACH_A + REACH_B * LOGP_HI:
            lp_hi = (lt - REACH_A) / REACH_B
            jmax = int((lp_hi - LOGP_LO) / STEP)
        jmax = max(0, min(npc - 1, jmax + PAD))
        rho, gad, cp = [], [], []
        for j in range(jmax + 1):
            r = row[j][2]
            if abs(r - SENTINEL) < 1e-3:
                sentinels.append((lt, row[j][1]))
                r = None
            rho.append(r)
            gad.append(row[j][9])
            # c_P = T (dS/dT)_P = S · (dlnS/dlnT)_P. 표의 5열(log S)과 8열이 그대로
            # 준다. 단위는 MJ/kg/K 이므로 SI 로 1e6 을 곱한다.
            cp.append(10.0 ** row[j][4] * row[j][7] * 1e6)
        rho_rows.append(rho)
        gad_rows.append(gad)
        cp_rows.append(cp)
        keep_rows.append(jmax + 1)

    if sentinels:
        print("WARNING: sentinels inside the baked region:", sentinels, file=sys.stderr)

    cells = sum(keep_rows)
    out = [
        "# Chabrier+ 2019 의 수소-헬륨 상태방정식 표 — 생성된 파일이다. 손으로 고치지 말 것",
        '"""Baked H/He equation of state, Chabrier, Mazevet & Soubiran 2019.',
        "",
        "**Generated by `engine/tools/make_hhe_table.py`; do not edit by hand.** The source is",
        "`TABLEEOS_HHE_TP_IVL_Y0.275_v1` from the archive the paper points at",
        "(perso.ens-lyon.fr/gilles.chabrier/DirEOS/DirEOS2019.tar.gz), which the README inside",
        "attributes to Chabrier, Mazevet & Soubiran 2019, ApJ 872, 51.",
        "",
        "**Y = 0.275, Z = 0.** The archive also offers Y_eff = 0.292, which is the same mixture",
        "with Z = 0.017 folded into the helium so that two components can stand in for three.",
        "This recipe already carries `envelope_z` and mixes metals in itself, so taking Y_eff",
        "would put them in twice — the trap this repository walked into with Jupiter's Z.",
        "",
        "Two quantities are kept: log rho and grad_ad = (dlnT/dlnP)_S. The second is why the",
        "envelope has a temperature at all — it is the published adiabatic gradient, so the",
        "recipe reads it instead of rebuilding one out of a Grueneisen parameter.",
        '"""',
        "",
        "LOGT_LO = %r" % LOGT_LO,
        "LOGP_LO = %r" % LOGP_LO,
        "STEP = %r" % STEP,
        "NT = %d" % nt,
        "NP = %d" % npc,
        "",
        "# 도달 가능 영역의 아래 경계: log T >= REACH_A + REACH_B * log P. 그 아래는 대류하는",
        "# 외피가 닿지 않고, 배포 표의 결함(밀도 자리의 sentinel 7칸, 0.1/0.5 로 눌린 grad_ad)이",
        "# 전부 거기 있다. 고치지 않고 거절한다 — 발표된 수를 손보는 것보다 영역을 말하는 쪽이다.",
        "REACH_A = %r" % REACH_A,
        "REACH_B = %r" % REACH_B,
        "",
        "# 등온선마다 굳힌 열의 개수. 도달 경계까지 + 보간 스텐실용 여유 %d칸." % PAD,
        "KEEP = %r" % (tuple(keep_rows),),
        "",
        "# log rho [g/cc]. 바깥 튜플이 등온선(log T = LOGT_LO + i*STEP), 안쪽이 압력.",
        "LOGRHO = (",
    ]
    for r in rho_rows:
        out.append("    (" + ",".join("%.4f" % v for v in r) + "),")
    out.append(")")
    out.append("")
    out.append("# grad_ad = (dlnT/dlnP)_S. 같은 격자.")
    out.append("GRAD_AD = (")
    for r in gad_rows:
        out.append("    (" + ",".join("%.4f" % v for v in r) + "),")
    out.append(")")
    out.append("")
    out.append("# 정압비열 c_P [J/kg/K] = S·(dlnS/dlnT)_P. 배포 표의 5열과 8열에서 온다.")
    out.append("# **혼합의 단열 기울기가 이것을 먹는다** — 엔트로피가 (P,T) 에서 가법이므로")
    out.append("# ∇_ad,mix 가 c_P 가중 평균으로 닫힌다 (Chabrier+ 2019 §V).")
    out.append("C_P = (")
    for r in cp_rows:
        out.append("    (" + ",".join("%.6g" % v for v in r) + "),")
    out.append(")")
    out.append("")
    out.append(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                 "hhe_table_tail.py")).read())

    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "hhe_table.py")
    body = "\n".join(out)
    return body, cells, path


if __name__ == "__main__":
    body, cells, path = main(sys.argv[1])
    print("cells", cells, "->", path, "(%d KB)" % (len(body) // 1024))
    sys.stdout.write("")
    open(path + ".part", "w").write(body)
