# Bethkenhagen, French & Redmer 2013 Table I 의 암모니아 상태방정식 표 — 생성된 파일이다. 손으로 고치지 말 것
"""Baked ammonia equation of state, Bethkenhagen, French & Redmer 2013.

**Generated by `engine/tools/make_ammonia_table.py`; do not edit by hand.** The source is
Appendix B, Table I of Bethkenhagen, French & Redmer 2013, *Equation of state and phase
diagram of ammonia at high pressures from ab initio simulations*, J. Chem. Phys. 138,
234504 (2013JChPh.138w4504B, doi 10.1063/1.4810883) — FT-DFT-MD pressure and internal
energy on a (rho, T) grid, parsed from the cached PDF's text layer and checked against the
printed page (`test_ammonia.py`). The printed table is the only form the data exist in.

**Convention.** The internal energy column INCLUDES the vibrational (nuclear-quantum)
correction u = u* + u_vc (their eq. (1); Appendix B; Fig. 7 caption). Bethkenhagen+ 2017
removed that correction from this data set for their own consistency; this module keeps
the printed values. Pressure carries no such correction — the paper neglected p_vc as small
for this data set "However, this should not be understood as a general result" (Sec. II B).

**Uncertainty.** "In general, the pressure is converged within an error bar of 2%, except
for the data points marked with asterisk, which have an uncertainty of up to 5%. The caloric
EOS is of the same quality as the pressure." (Appendix B). The five flagged points are
carried as a flag on the row and reported by `uncertainty(rho, t)`.

**Grid.** Ragged: 500 K has densities 0.5-1.5, 700 K 0.5-2.0, 1000 K and above 0.5-3.0
g/cm^3. The six absent cold-dense cells are outside the table, not interpolated across.
Along an isotherm log p is linear in log rho and u is linear in log rho; between isotherms
both are linear in T. Units inside the tuples are the paper's (g/cm^3, K, GPa, kJ/g); the
accessors take and return SI.
"""

SOURCE = "Bethkenhagen, French & Redmer 2013 (2013JChPh.138w4504B) Appendix B Table I"
U_INCLUDES_VIBRATIONAL_CORRECTION = True
P_UNCERTAINTY = 0.02           # converged within 2 %, Appendix B
P_UNCERTAINTY_FLAGGED = 0.05   # asterisked points, up to 5 %
T_MIN_K = 500.0
T_MAX_K = 10000.0
P_MAX_PA = 333.2e9             # the table's largest pressure (3.0 g/cm^3, 10 000 K)
N_POINTS = 93
N_FLAGGED = 5

import math

# 등온선 온도 [K].
T_K = (500, 700, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 10000)

# 등온선마다 (rho [g/cm^3], p [GPa], u [kJ/g], 5 % 표시) — 인쇄된 순서대로.
ISOTHERMS = (
    (  # 500 K
        (0.5, 0.309, -105.69, False),
        (0.75, 1.575, -105.78, False),
        (1.0, 4.97, -105.33, False),
        (1.3, 12.61, -104.16, False),
        (1.5, 22.13, -102.63, False),
    ),
    (  # 700 K
        (0.5, 0.536, -105.12, False),
        (0.75, 1.987, -104.9, False),
        (1.0, 5.595, -104.33, False),
        (1.3, 13.68, -103.33, False),
        (1.5, 23.5, -101.95, False),
        (1.8, 45.07, -98.512, False),
        (2.0, 64.57, -95.843, False),
    ),
    (  # 1000 K
        (0.5, 0.749, -103.94, False),
        (0.75, 2.514, -103.9, False),
        (1.0, 6.553, -103.24, False),
        (1.3, 16.4, -101.6, False),
        (1.5, 25.07, -100.5, False),
        (1.8, 46.96, -97.24, False),
        (2.0, 66.32, -94.413, False),
        (2.5, 135.1, -85.619, False),
        (3.0, 237.0, -74.05, False),
    ),
    (  # 2000 K
        (0.5, 1.32, -100.32, False),
        (0.75, 3.696, -99.876, False),
        (1.0, 9.084, -99.037, False),
        (1.3, 20.25, -96.942, False),
        (1.5, 29.4, -95.758, False),
        (1.8, 51.72, -92.251, False),
        (2.0, 71.78, -89.348, False),
        (2.5, 143.1, -80.317, False),
        (3.0, 247.1, -68.708, False),
    ),
    (  # 3000 K
        (0.5, 1.906, -96.113, False),
        (0.75, 5.111, -95.462, False),
        (1.0, 10.78, -94.265, False),
        (1.3, 22.83, -91.815, False),
        (1.5, 34.4, -89.106, False),
        (1.8, 59.4, -84.818, False),
        (2.0, 76.45, -83.814, False),
        (2.5, 150.0, -74.607, False),
        (3.0, 256.0, -62.896, False),
    ),
    (  # 4000 K
        (0.5, 3.15, -89.81, True),
        (0.75, 7.64, -87.98, True),
        (1.0, 14.36, -85.86, True),
        (1.3, 25.86, -83.838, False),
        (1.5, 38.11, -81.254, False),
        (1.8, 63.67, -77.635, False),
        (2.0, 85.92, -74.501, False),
        (2.5, 162.2, -64.754, False),
        (3.0, 269.2, -52.984, False),
    ),
    (  # 5000 K
        (0.5, 4.45, -83.05, True),
        (0.75, 9.0, -80.9, True),
        (1.0, 16.11, -78.258, False),
        (1.3, 28.48, -75.368, False),
        (1.5, 41.38, -73.493, False),
        (1.8, 67.73, -69.583, False),
        (2.0, 91.34, -66.402, False),
        (2.5, 169.8, -56.982, False),
        (3.0, 279.3, -45.61, False),
    ),
    (  # 6000 K
        (0.5, 5.499, -75.881, False),
        (0.75, 10.07, -73.339, False),
        (1.0, 17.11, -70.786, False),
        (1.3, 30.92, -67.969, False),
        (1.5, 44.68, -66.017, False),
        (1.8, 72.69, -62.289, False),
        (2.0, 96.7, -59.346, False),
        (2.5, 177.9, -50.496, False),
        (3.0, 289.8, -39.021, False),
    ),
    (  # 7000 K
        (0.5, 5.942, -68.485, False),
        (0.75, 11.06, -65.817, False),
        (1.0, 18.71, -63.687, False),
        (1.3, 33.88, -61.532, False),
        (1.5, 47.92, -59.69, False),
        (1.8, 77.54, -56.548, False),
        (2.0, 102.7, -53.746, False),
        (2.5, 186.3, -44.838, False),
        (3.0, 300.8, -33.503, False),
    ),
    (  # 8000 K
        (0.5, 6.261, -60.767, False),
        (0.75, 11.95, -59.071, False),
        (1.0, 20.69, -57.593, False),
        (1.3, 36.77, -55.805, False),
        (1.5, 51.96, -54.356, False),
        (1.8, 82.81, -51.015, False),
        (2.0, 109.0, -48.431, False),
        (2.5, 194.7, -39.822, False),
        (3.0, 311.9, -28.337, False),
    ),
    (  # 10000 K
        (0.5, 7.7, -46.837, False),
        (0.75, 14.42, -46.553, False),
        (1.0, 24.75, -46.675, False),
        (1.3, 43.27, -45.714, False),
        (1.5, 60.51, -44.612, False),
        (1.8, 94.24, -41.54, False),
        (2.0, 122.0, -38.96, False),
        (2.5, 212.1, -30.274, False),
        (3.0, 333.2, -18.953, False),
    ),
)

# 보간 오차, leave-one-out 으로 잰 것: 격자점 하나를 빼고 이웃에서 예측한 값과의 차의
# 최악. 격자 간격이 두 배가 된 자리의 수이므로 실제 격자 사이의 오차는 이보다 작다 —
# 선형 보간의 오차가 간격의 제곱이면 약 1/4. test_ammonia.py 가 다시 잰다.
INTERP_P_LOO_WORST = 0.1726       # relative, at rho 0.5 T 3000 (along T)
INTERP_U_LOO_WORST_KJG = 2.450   # absolute kJ/g, at rho 2.5 T 8000
# 같은 것을 맨틀 영역(rho >= 1.0 g/cm^3, T >= 2000 K)에서만.
MANTLE_RHO_MIN_GCC = 1.0
MANTLE_T_MIN_K = 2000.0
INTERP_P_LOO_MANTLE = 0.0874      # relative, at rho 1.0 T 3000 (along T)
INTERP_U_LOO_MANTLE_KJG = 2.450  # absolute kJ/g, at rho 2.5 T 8000


def _bracket_t(t_k):
    """(i, j): the isotherms bracketing T. On an isotherm exactly, i == j — that isotherm
    alone, so the ragged edge of a neighbour does not narrow the domain there."""
    if t_k < T_MIN_K or t_k > T_MAX_K:
        raise ValueError(f"{t_k:.0f} K is outside {SOURCE} ({T_MIN_K:.0f}-{T_MAX_K:.0f} K)")
    for i, tk in enumerate(T_K):
        if t_k == tk:
            return i, i
    for i in range(len(T_K) - 1):
        if T_K[i] < t_k < T_K[i + 1]:
            return i, i + 1
    raise ValueError


def _interp_iso(iso, rho_gcc):
    rs = [r for r, _p, _u, _f in iso]
    # 격자점 위의 반올림 한 비트는 안으로 접는다 (density 의 이분법이 exp(log) 로 되돌아올 때).
    if rs[0] * (1.0 - 1e-12) <= rho_gcc < rs[0]:
        rho_gcc = rs[0]
    elif rs[-1] < rho_gcc <= rs[-1] * (1.0 + 1e-12):
        rho_gcc = rs[-1]
    if rho_gcc < rs[0] or rho_gcc > rs[-1]:
        raise ValueError(f"rho {rho_gcc:.3f} g/cm^3 is outside this isotherm of {SOURCE}")
    for j in range(len(rs) - 1):
        if rs[j] <= rho_gcc <= rs[j + 1]:
            r0, p0, u0, f0 = iso[j]
            r1, p1, u1, f1 = iso[j + 1]
            if rho_gcc == r0:          # 격자점은 굳힌 값 그대로 (exp/log 왕복의 반올림 없이)
                return p0, u0, f0
            if rho_gcc == r1:
                return p1, u1, f1
            x = (math.log(rho_gcc) - math.log(r0)) / (math.log(r1) - math.log(r0))
            return (math.exp(math.log(p0) + x * (math.log(p1) - math.log(p0))),
                    u0 + x * (u1 - u0), f0 or f1)
    raise ValueError


def _eval(rho_kgm3, t_k):
    """(p [GPa], u [kJ/g], flagged) at (rho, T). Raises ValueError outside the table."""
    i, j = _bracket_t(t_k)
    r = rho_kgm3 / 1e3
    p0, u0, f0 = _interp_iso(ISOTHERMS[i], r)
    if i == j:
        return p0, u0, f0
    p1, u1, f1 = _interp_iso(ISOTHERMS[j], r)
    x = (t_k - T_K[i]) / (T_K[j] - T_K[i])
    return p0 + x * (p1 - p0), u0 + x * (u1 - u0), f0 or f1


def pressure(rho_kgm3, t_k):
    """p [Pa] at rho [kg/m^3], T [K]."""
    return _eval(rho_kgm3, t_k)[0] * 1e9


def internal_energy(rho_kgm3, t_k):
    """u [J/kg] at rho [kg/m^3], T [K]. Includes the vibrational correction (see module doc)."""
    return _eval(rho_kgm3, t_k)[1] * 1e6


def uncertainty(rho_kgm3, t_k):
    """The paper's stated relative uncertainty of p (and u) at this point: 5 % if any grid
    point the interpolation touches is asterisked, else 2 %."""
    return P_UNCERTAINTY_FLAGGED if _eval(rho_kgm3, t_k)[2] else P_UNCERTAINTY


def rho_bounds(t_k):
    """(rho_lo, rho_hi) [kg/m^3] the table covers at T: the intersection of the two
    bracketing isotherms' density ranges (the grid is ragged below 1000 K)."""
    i, j = _bracket_t(t_k)
    a, b = ISOTHERMS[i], ISOTHERMS[j]
    return max(a[0][0], b[0][0]) * 1e3, min(a[-1][0], b[-1][0]) * 1e3


def p_bounds(t_k):
    """(p_lo, p_hi) [Pa] the table covers at T."""
    lo, hi = rho_bounds(t_k)
    return pressure(lo, t_k), pressure(hi, t_k)


def in_domain(p_pa, t_k):
    if t_k < T_MIN_K or t_k > T_MAX_K:
        return False
    lo, hi = p_bounds(t_k)
    return lo <= p_pa <= hi


def density(p_pa, t_k):
    """rho [kg/m^3] at p [Pa], T [K], by bisection of the isotherm-interpolated p(rho).
    Raises ValueError, naming the table, outside its (ragged) domain."""
    lo, hi = rho_bounds(t_k)
    p_lo, p_hi = pressure(lo, t_k), pressure(hi, t_k)
    if p_lo * (1.0 - 1e-12) <= p_pa < p_lo:      # 가장자리의 반올림 한 비트는 안으로
        p_pa = p_lo
    elif p_hi < p_pa <= p_hi * (1.0 + 1e-12):
        p_pa = p_hi
    if p_pa < p_lo or p_pa > p_hi:
        raise ValueError(f"{p_pa / 1e9:.2f} GPa at {t_k:.0f} K is outside {SOURCE} "
                         f"({p_lo / 1e9:.3f}-{p_hi / 1e9:.1f} GPa at this temperature)")
    a, b = math.log(lo), math.log(hi)
    for _ in range(60):
        m = 0.5 * (a + b)
        if pressure(math.exp(m), t_k) < p_pa:
            a = m
        else:
            b = m
    return math.exp(0.5 * (a + b))
