# Reinhardt+ 2022 의 물 액체–고체 공존선과 얼음 VII′–VII″ 공존선 — 생성된 파일이다. 손으로 고치지 말 것
"""Baked coexistence lines of high-pressure water, Reinhardt+ 2022.

**Generated by `engine/tools/make_ice_melt_table.py`; do not edit by hand.** The source
is the data repository of Reinhardt, Bethkenhagen, Coppari, Millot, Hamel & Cheng 2022,
*Thermodynamics of high-pressure ice phases explored with atomistic simulations*,
Nat Commun 13, 4707 (2022NatCo..13.4707R, arXiv:2203.12897):
https://github.com/BingqingCheng/highP-ice at commit 2623af1c423ad89c3ff9fd13962a9e73b9d40cf2.

Points are (P [GPa], T [K]) as published, in the order published. The third field of
the liquid line marks the points the paper starred as benchmarked by direct coexistence.
Machine-learned potential fitted to PBE DFT — a simulation, not a measurement. The
consumer (`eos.py`) interpolates linearly between points and grades the answer analog.
"""

# figs-1-and-S1/coex-line-liquid.dat
LIQUID_LINE = (
    (10.0, 408.485, False),
    (15.0, 643.028, False),
    (20.0, 875.0, True),
    (22.7282, 1000.0, False),
    (26.0, 1133.0, True),
    (30.0, 1237.1, False),
    (33.9, 1377.0, False),
    (36.2, 1453.0, False),
    (42.3, 1659.0, False),
    (47.0, 1800.0, True),
    (52.4, 1953.0, False),
)

# figs-1-and-S1/coex-line-superionic-ice.dat
VII1_VII2_LINE = (
    (20.0, 856.376),
    (26.0, 1014.3),
    (30.0, 1149.87),
    (40.0, 1337.21),
    (50.0, 1568.62),
    (60.0, 1755.37),
    (70.0, 1920.78),
)

# figs-1-and-S1/coex-direct-coexistence.dat
DIRECT_COEXISTENCE = (
    (15.0, 650.0),
    (20.0, 875.0),
    (22.0, 960.0),
    (26.0, 1133.0),
    (40.0, 1592.5),
    (47.0, 1800.0),
)

DATA_COMMIT = '2623af1c423ad89c3ff9fd13962a9e73b9d40cf2'
TRIPLE_POINT_GPA_K = (20.0, 875.0)   # 논문 §IV 의 액체–VII′–VII″ 삼중점
