# 선언된 맨틀 포텐셜 온도가 함의하는 표면 열류 — Nimmo+ 2004 식 34–36 (상단 경계층), 방사성 예산과의 일관성 판정 (Brief 46)
"""Surface heat flux implied by a declared mantle potential temperature — Nimmo+ 2004 eqs 34–36.

    from mantle_flux import implied_flux, consistency
    implied_flux(t_m_k=1600.0, g=9.8, r_m=6.4e6)   -> δ_t 58.8 km, F_t 0.0768 W/m², Q_M 39.5 TW

The top thermal boundary layer by the local-Rayleigh-number approach (Nimmo, Price, Brodholt &
Gubbins 2004, GJI 156, 363, extraction lines 655–693):

    δ_t = [Ra_c κ_t η_t(T_m) / (ρ_m g α_m (T_m − T_s))]^(1/3)      (34)
    η_t(T_m) = η₀ · exp[−ζ (T_m − T₀)]                               (35)
    F_t = k_t (T_m − T_s) / δ_t                                       (36)

Algebraic in T_m, top layer only (f and T₁ belong to eq. 39, the bottom layer), nothing time-evolved.
Constants from Table 2 (read with `pdftotext -layout`; the plain extraction interleaves the columns).

⚠ Conditions that ride on every number out of here:
* **Calibrated at source.** The parameterisation was tuned on four simultaneous present-day Earth
  constraints — entropy production, inner-core radius, and *"the present-day mantle temperature,
  viscosity and heat flux"* — plus densities adopted so the outer core agrees with PREM. A value from
  it is *consistent with an Earth-calibrated parameterisation*, never *the body's actual heat flux*.
* **`k_t` is derived, not printed — and the authors did the conversion themselves.** *"k_t is the
  thermal conductivity at the top of the mantle"* has no value anywhere in the paper (Table 1's
  50 ± 20 W/(m·K) is the core's); but extraction line 944 says *"The values of κ_t and κ_b are based on
  Hofmeister's (1999) calculations of the increase in **conductivity** with depth"* — so κ_t was made
  from a conductivity, and κ_t·ρ_m·C_pm = 3.456 W/(m·K) **undoes their step** rather than inventing one.
  That sentence is the primary licence. The check: inverting the chain for the paper's own present-day
  ~42 TW gives T_m = 1614 K, against the paper's **own printed** present-day potential temperature,
  *"1330 °C (McKenzie & Bickle 1988)"* = 1603 K (line 1294, same paragraph as the 42 TW) — **+11 K,
  0.7 %, between two numbers the paper prints.** What the closure does not do: with Q ∝ k_t and
  d ln Q/dT ≈ 0.0043 K⁻¹, an 11 K agreement constrains k_t to ~5 %, and 1330 °C is quoted to the degree
  at best, so realistically ±10 % — the width of the textbook 3–4 band. **It confirms the
  transcription; it does not sharpen k_t.**
* **ζ originates here with ± 0.5**, which Nimmo & Primack 2020 dropped; its own basis is deferred to
  Solomatov 1995 / Karato & Wu 1993 (unobtained). Forward, at fixed T_m, Q_M moves ±4 % across the
  band; inverted for a flux, T_m moves ±1 %. **Two more sensitivities, same size, both directions
  forward**: α_m's printed ± 0.3 ×10⁻⁵ moves Q_M **±4.5 %** (Q ∝ α^{1/3}); and **T_s = 293 K is Earth's,
  declared for every body** — it enters as (T_m − T_s)^{4/3}, so a 200 K surface is **+10 %**. T_s is the
  one constant here that is obviously not the roster's.
* **The verdict is a consistency check on a declaration, not a refusal.** The implied flow and the
  radiogenic budget are not required to match; **secular cooling is the expected difference** (the
  paper: Earth *"loses heat roughly twice as fast as it is being generated by radioactive decay"*).
"""
from __future__ import annotations

import math

# ── Nimmo+ 2004 Table 2, top-layer constants (layout extraction) ────────────────────
RA_C = 600.0                 # critical Rayleigh number (eq. 34) — originates here, deferred to Nimmo & Stevenson 2000
KAPPA_T = 6.0e-7             # m²/s, mantle thermal diffusivity (eq. 34)
ETA_0 = 1.0e21               # Pa·s, viscosity at the reference temperature (eq. 35)
ZETA = 1.0e-2                # K⁻¹, "a quantity related to the activation energy" (eq. 35)
ZETA_RANGE = (0.5e-2, 1.5e-2)   # the printed ± 0.5 — kept; N&P 2020 dropped it
T_0 = 1573.0                 # K, reference temperature (eq. 35)
RHO_M = 4800.0               # kg/m³ (eq. 34)
ALPHA_M = 2.2e-5             # K⁻¹ (eq. 34), printed ± 0.3
C_PM = 1200.0                # J/(kg·K) (eq. 32)
T_S = 293.0                  # K, surface temperature (eq. 34) — Earth's, declared for every body
# NOT PRINTED — derived by the identity κ = k/(ρ C_p) from Table 2. Labelled so wherever it appears.
K_T = KAPPA_T * RHO_M * C_PM   # 3.456 W/(m·K)
EARTH_R_P = 6.4e6            # m, Table 2 R_p (the paper's Earth); the recipe uses the body's own R
EARTH_G = 9.8                # m/s², Table 2
PAPER_PRESENT_DAY_Q_TW = 42.0   # "The present-day heat flux is approximately 42 TW (Sclater et al., 1980)"

# The consistency labels. The bounded quantity has a name: implied/radiogenic = 1/Urey ratio. The
# ceiling is expressed as a UREY-RATIO FLOOR so the declaration is in the units the literature argues
# about. The paper licenses "roughly twice" (Ur ≈ 0.5); the floor is set at the soft "roughly 2–3" that
# sentence actually allows — Ur ≥ 1/3, ratio ≤ 3 — because nothing held here grounds any sharper edge,
# and (audit, from memory, NOT transcribed) much of the literature puts Earth's mantle Urey ratio below
# 0.4, so a 2.5 ceiling would have flagged a body sitting where a large part of the field puts Earth.
# The edge is soft and says so. Request list: Korenaga 2008 (2008RvGeo..46.2007K) and Jaupart,
# Labrosse & Mareschal 2007 (2007mady.book..253J) — ADS title-checked, not read.
UREY_FLOOR = 1.0 / 3.0
SECULAR_RATIO_MAX = 1.0 / UREY_FLOOR       # 3.0
CONSISTENT = "consistent-within-secular-gap"
TOO_HOT = "declaration-implies-more-heat-than-secular-cooling-allows"
TOO_COLD = "declaration-implies-less-than-radiogenic"
NO_T = "cannot-say (no potential temperature declared)"
NO_BUDGET = "cannot-say (no radiogenic budget)"
CONDITION = ("Nimmo+ 2004 eqs 34–36, calibrated at source on present-day Earth (+ PREM); k_t derived "
             "as κ_t·ρ_m·C_pm (not printed), T_s = 293 K declared; ζ carries the paper's ± 0.5; the "
             "verdict is a consistency check on the declared potential temperature, secular cooling is "
             "the expected difference, and none of it is the body's actual heat flux")


def viscosity(t_m_k: float, zeta: float = ZETA) -> float:
    """eq. 35 [Pa·s]."""
    return ETA_0 * math.exp(-zeta * (t_m_k - T_0))


def implied_flux(t_m_k: float, g: float, r_m: float, zeta: float = ZETA) -> dict:
    """eqs 34–36 at a declared potential temperature. Returns δ_t [m], F_t [W/m²], Q_M [W]."""
    if t_m_k <= T_S:
        raise ValueError(f"T_m {t_m_k} K 가 표면온도 {T_S} K 아래 — 경계층이 정의되지 않는다")
    d_t = (RA_C * KAPPA_T * viscosity(t_m_k, zeta) / (RHO_M * g * ALPHA_M * (t_m_k - T_S))) ** (1.0 / 3.0)
    f_t = K_T * (t_m_k - T_S) / d_t
    return {"delta_t_m": d_t, "f_t_w_m2": f_t, "q_m_w": f_t * 4.0 * math.pi * r_m ** 2}


def invert_for_flow(q_w: float, g: float = EARTH_G, r_m: float = EARTH_R_P,
                    zeta: float = ZETA, lo: float = 1000.0, hi: float = 2500.0) -> float:
    """T_m [K] whose implied Q_M equals q_w — the transcription check (42 TW → 1614 K)."""
    for _ in range(80):
        mid = 0.5 * (lo + hi)
        if implied_flux(mid, g, r_m, zeta)["q_m_w"] < q_w:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


def consistency(t_m_k: float | None, radiogenic_w: float | None, g: float, r_m: float) -> dict:
    """The verdict: implied flow at the declared T_m against the radiogenic budget, with the ζ band.
    Returns values + notes; every value labelled by CONDITION."""
    if not t_m_k or t_m_k <= T_S:
        return {"verdict": NO_T, "delta_t_km": None, "f_t_w_m2": None, "q_m_w": None,
                "ratio": None, "notes": ("heat-flow consistency: cannot say — no potential temperature declared "
                                        "(nothing to imply a flux from).",)}
    core = implied_flux(t_m_k, g, r_m)
    band = [implied_flux(t_m_k, g, r_m, z)["q_m_w"] for z in ZETA_RANGE]
    out = {"delta_t_km": core["delta_t_m"] / 1e3, "f_t_w_m2": core["f_t_w_m2"], "q_m_w": core["q_m_w"],
           "ratio": None}
    if not radiogenic_w or radiogenic_w <= 0.0:
        out["verdict"] = NO_BUDGET
        out["notes"] = (f"heat-flow consistency: the declared T_m {t_m_k:.0f} K implies δ_t {out['delta_t_km']:.1f} km, "
                        f"F_t {core['f_t_w_m2']:.4f} W/m², Q_M {core['q_m_w'] / 1e12:.2f} TW (ζ band "
                        f"{band[0] / 1e12:.1f}–{band[1] / 1e12:.1f} TW) — no radiogenic budget to compare against. "
                        + CONDITION + ".",)
        return out
    ratio = core["q_m_w"] / radiogenic_w
    ratio_band = (min(band) / radiogenic_w, max(band) / radiogenic_w)
    out["ratio"] = ratio
    urey = 1.0 / ratio
    out["urey_ratio"] = urey
    if ratio < 1.0:
        verdict = TOO_COLD
    elif ratio > SECULAR_RATIO_MAX:
        verdict = TOO_HOT
    else:
        verdict = CONSISTENT
    out["verdict"] = verdict
    out["notes"] = (
        f"heat-flow consistency ({verdict}): the declared potential temperature {t_m_k:.0f} K implies, through "
        f"Nimmo+ 2004 eqs 34–36, a top boundary layer δ_t {out['delta_t_km']:.1f} km, F_t {core['f_t_w_m2']:.4f} W/m², "
        f"Q_M {core['q_m_w'] / 1e12:.2f} TW (ζ 0.5–1.5 ×10⁻²: {band[0] / 1e12:.1f}–{band[1] / 1e12:.1f} TW); the "
        f"radiogenic budget is {radiogenic_w / 1e12:.2f} TW, ratio {ratio:.2f} (band {ratio_band[0]:.2f}–{ratio_band[1]:.2f}; "
        f"Urey ratio {urey:.2f}). "
        + {CONSISTENT: f"Inside the secular-cooling gap (ratio 1–{SECULAR_RATIO_MAX:.0f}, i.e. Urey ratio ≥ {UREY_FLOOR:.2f} — a "
                       "declared, soft edge after the paper's 'roughly twice'): consistent with an Earth-calibrated "
                       "parameterisation; for Earth itself this reproduces the calibration. Secular cooling is the "
                       "expected difference. Not a passed test of the body.",
           TOO_HOT: f"Above {SECULAR_RATIO_MAX:.0f}× the budget (Urey ratio below {UREY_FLOOR:.2f}): the declared temperature implies more heat leaving than "
                    "radioactivity plus plausible secular cooling supply — the declaration is saying something the "
                    "body cannot do for long. Not a refusal; a flag on the declaration.",
           TOO_COLD: "Below the radiogenic budget alone: the declared temperature is colder than the body's own heat "
                     "production can sustain — heat would accumulate. Not a refusal; a flag on the declaration."}[verdict]
        + f" α_m ± 0.3 moves the implied flow ±4.5 %; T_s = 293 K is declared (Earth's) and a 200 K surface would add +10 %."
        + " " + CONDITION + ".",)
    return out
