# Phase 4 discoverability 결정 → ResearchBodies RESEARCHBODIES MM 패치 emitter
"""Emit the NearStars ResearchBodies discoverability patch.

Reads a structured `discoverability:` block from Phase 4 system files:

  phase4/<system>.yaml
      discoverability:
        - body: AlphaCentauriA      # exact Kopernicus internal body name
          category: naked_eye       # naked_eye|confirmed|candidate|disputed|fictional
        - body: Polyphemus
          category: candidate
          message: "JWST/MIRI ... candidate S1."
          ref: "2025arXiv250803812S"

Maps each category to an IGNORELEVELS start-visibility tuple (canonical
mapping, revised 2026-06-22 — see SCHEME below) and composes the ONDISCOVERY
message, then writes one combined MM patch:

  dist/NearStars-Configs/Patches/ResearchBodies/NearStars.cfg

The patch is `RESEARCHBODIES:NEEDS[ResearchBodies&Kopernicus] { loadAs = mod
... }`. `loadAs = mod` is mandatory or RB silently ignores the data
(Database.cs:289). Schema details: see this skill's references/.

Usage:
    python3 .claude/skills/researchbodies-cfg/scripts/emit_researchbodies_cfg.py --dry-run
    python3 .claude/skills/researchbodies-cfg/scripts/emit_researchbodies_cfg.py
    python3 .claude/skills/researchbodies-cfg/scripts/emit_researchbodies_cfg.py --input some/file.yaml --dry-run
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[4]
DEFAULT_INPUTS = sorted((ROOT / "phase4").glob("*.yaml"))
OUT_DIR = ROOT / "dist" / "NearStars-Configs" / "Patches" / "ResearchBodies"
OUT_FILE = OUT_DIR / "NearStars.cfg"

# category → (easy, normal, medium, hard) start-visibility.
# Canonical mapping, revised 2026-06-22: stars always visible; every planet
# (confirmed/candidate/disputed) is discover-by-observation (Easy shows it,
# Normal+ hides it); fictional moons always discovered. See db-mapping.md.
SCHEME = {
    "naked_eye": (True, True, True, True),
    "confirmed": (True, False, False, False),
    "candidate": (True, False, False, False),
    "disputed": (True, False, False, False),
    "fictional": (False, False, False, False),
}


def _tuple_str(t: tuple[bool, bool, bool, bool]) -> str:
    return " ".join("true" if b else "false" for b in t)


def collect(inputs: list[Path]) -> tuple[list[dict], list[str]]:
    """Return (entries, warnings). Each entry: body, category, message, ref, src."""
    entries: list[dict] = []
    warnings: list[str] = []
    seen: dict[str, str] = {}  # body -> source file (duplicate guard)

    for path in inputs:
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(doc, dict):
            continue
        disc = doc.get("discoverability")
        if not disc:
            continue
        for row in disc:
            body = (row.get("body") or "").strip()
            cat = (row.get("category") or "").strip()
            if not body:
                warnings.append(f"{path.name}: entry with no `body` — skipped")
                continue
            if cat not in SCHEME:
                warnings.append(
                    f"{path.name}: {body!r} has unknown category {cat!r} "
                    f"(expected {'/'.join(SCHEME)}) — skipped"
                )
                continue
            if body in seen:
                warnings.append(
                    f"{path.name}: duplicate body {body!r} (already in {seen[body]}) — skipped"
                )
                continue
            seen[body] = path.name
            msg = (row.get("message") or "").strip()
            ref = (row.get("ref") or "").strip()
            if cat in ("candidate", "disputed") and not ref:
                warnings.append(
                    f"{path.name}: {body!r} is {cat} but has no `ref` (detection-paper "
                    f"bibcode) — discovery message will not cite a source"
                )
            # append bibcode to message if given and not already present
            if msg and ref and ref not in msg:
                msg = f"{msg} [{ref}]"
            entries.append({"body": body, "category": cat, "message": msg, "src": path.name})

    entries.sort(key=lambda e: e["body"])
    return entries, warnings


def render(entries: list[dict]) -> str:
    ondiscovery = [e for e in entries if e["message"]]
    lines: list[str] = []
    lines.append("// NearStars discoverability — ResearchBodies patch (optional layer).")
    lines.append("// Generated by .claude/skills/researchbodies-cfg/scripts/emit_researchbodies_cfg.py")
    lines.append("// Body name = exact Kopernicus internal name. Grading: stars visible, planets discover-by-observation (Easy-visible), fictional always discover.")
    lines.append("RESEARCHBODIES:NEEDS[ResearchBodies&Kopernicus]")
    lines.append("{")
    lines.append("\tloadAs = mod")
    lines.append("\tname = NearStars")
    lines.append("")
    if ondiscovery:
        lines.append("\tONDISCOVERY")
        lines.append("\t{")
        for e in ondiscovery:
            lines.append(f"\t\t{e['body']} = {e['message']}")
        lines.append("\t}")
        lines.append("")
    lines.append("\tIGNORELEVELS")
    lines.append("\t{")
    lines.append("\t\t// body = easy normal medium hard")
    for e in entries:
        tup = _tuple_str(SCHEME[e["category"]])
        lines.append(f"\t\t{e['body']} = {tup}\t// {e['category']}")
    lines.append("\t}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--dry-run", action="store_true", help="print to stdout, do not write")
    ap.add_argument("--input", action="append", default=[],
                    help="input yaml path(s); default = phase4/*.yaml")
    args = ap.parse_args()

    inputs = [Path(p) for p in args.input] if args.input else DEFAULT_INPUTS
    entries, warnings = collect(inputs)

    for w in warnings:
        print(f"WARNING: {w}", file=sys.stderr)

    if not entries:
        print("No discoverability decisions found in inputs. Nothing to emit.", file=sys.stderr)
        return 0

    cfg = render(entries)

    if args.dry_run:
        print(cfg)
        print(f"// {len(entries)} bodies from {len({e['src'] for e in entries})} system(s)",
              file=sys.stderr)
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(cfg, encoding="utf-8")
    print(f"Wrote {OUT_FILE} ({len(entries)} bodies)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
