# Phase 2/3 보고서 인덱스 + 매니페스트 생성기 (docs/reports.html + docs/reports-manifest.json)
"""Scan docs/phase2/ and docs/phase3/ for autogenerated reports, then
emit a discovery page and a machine-readable manifest.

Outputs:
  - docs/reports.html              # human-readable listing (bilingual)
  - docs/reports-manifest.json     # machine-readable, consumed by docs/index.html

Phase 2 reports live at docs/phase2/<host-slug>.html and cover one host
each. Phase 3 reports live at docs/phase3/<planet-slug>.html and cover
one planet. Host ↔ planet pairing is inferred by slug prefix
(``trappist-1-d`` belongs to host ``trappist-1``); display names come
from the DB so the table shows ``TRAPPIST-1`` rather than ``trappist-1``.

Usage:
    python3 scripts/pipeline/build_reports_index.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


def to_url_slug(name: str) -> str:
    s = name.lower()
    s = re.sub(r'[^a-z0-9]+', '-', s)
    return s.strip('-')


def load_db_names(repo: Path) -> tuple[dict[str, str], dict[str, tuple[str, str]]]:
    """Return ({host_slug: host_display_name}, {planet_slug: (host_slug, planet_letter)}).

    The host display name comes from stellar_props_curated keys.
    Planet letter is the suffix after the host slug.
    """
    stellar = json.loads((repo / 'db' / 'stellar_props_curated.json').read_text())
    planets = json.loads((repo / 'db' / 'planets_curated.json').read_text())

    host_names: dict[str, str] = {}
    for host_name in stellar:
        host_names[to_url_slug(host_name)] = host_name
    # planets_curated keys are host names; the planet name is in each entry.
    planet_map: dict[str, tuple[str, str]] = {}
    for host_name, entries in planets.items():
        host_slug = to_url_slug(host_name)
        host_names.setdefault(host_slug, host_name)
        for entry in entries:
            pname = entry.get('pl_name')
            if not pname: continue
            psl = to_url_slug(pname)
            # planet letter: the bit after the host slug + '-'
            letter = psl[len(host_slug) + 1:] if psl.startswith(host_slug + '-') else psl
            planet_map[psl] = (host_slug, letter)
    return host_names, planet_map


def scan_reports(repo: Path):
    """Walk docs/phase2/ and docs/phase3/ for per-planet/per-host .html, returning slugs.

    Skip infrastructure pages — underscore-prefixed (e.g. ``_demo-hex-viz``)
    and the manual-fetch index — since those aren't per-planet reports.
    """
    phase2_dir = repo / 'docs' / 'phase2'
    phase3_dir = repo / 'docs' / 'phase3'
    skip = {'manual-fetch'}

    def is_report(p: Path) -> bool:
        return not p.stem.startswith('_') and p.stem not in skip

    phase2_slugs = sorted(p.stem for p in phase2_dir.glob('*.html') if is_report(p)) if phase2_dir.exists() else []
    phase3_slugs = sorted(p.stem for p in phase3_dir.glob('*.html') if is_report(p)) if phase3_dir.exists() else []
    return phase2_slugs, phase3_slugs


def build_manifest(host_names, planet_map, phase2_slugs, phase3_slugs):
    """Group by host. Returns {host_display_name: {phase2: path?, phase3: {letter: path}}}."""
    manifest: dict[str, dict] = {}

    for slug in phase2_slugs:
        host = host_names.get(slug, slug)
        manifest.setdefault(host, {'phase2': None, 'phase3': {}})
        manifest[host]['phase2'] = f'phase2/{slug}.html'

    for slug in phase3_slugs:
        if slug in planet_map:
            host_slug, letter = planet_map[slug]
        elif slug in host_names:
            # star-level synthesis (slug matches a host name exactly).
            # 별 자체에 대한 합성 문서. 시스템 그룹 안에서 ★ letter 로 정렬.
            host_slug, letter = slug, '★'
        else:
            # fall back to last-token split
            parts = slug.rsplit('-', 1)
            host_slug, letter = (parts[0], parts[1]) if len(parts) == 2 else (slug, '?')
        host = host_names.get(host_slug, host_slug)
        manifest.setdefault(host, {'phase2': None, 'phase3': {}})
        manifest[host]['phase3'][letter] = f'phase3/{slug}.html'

    return manifest


PAGE_TEMPLATE = r'''<!DOCTYPE html>
<!-- NearStars reports index — autogenerated by scripts/pipeline/build_reports_index.py -->
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title data-i18n="title"></title>
<link rel="stylesheet" href="style.css">
<style>
main { max-width: 980px }
.rt { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 6px }
.rt th { padding: 9px 12px; background: var(--bg-card-alt); color: var(--fg-dim); font-size: 10.5px; text-transform: uppercase; text-align: left; font-weight: 700; letter-spacing: .5px; border-bottom: 1px solid var(--bd-strong) }
.rt td { padding: 8px 12px; border-top: 1px solid var(--bd-soft); color: #b0c4d8; font-family: var(--mono); font-size: 12.5px; vertical-align: top }
.rt td.sys { font-family: var(--sans); color: var(--fg-emph); font-weight: 600 }
.rt a { color: var(--accent) }
.rt a:hover { text-decoration: underline }
.pill { display: inline-block; padding: 2px 9px; border-radius: 10px; font-size: 11px; font-weight: 700; letter-spacing: .3px; margin-right: 4px }
.pill-p2 { background: #1a2f44; color: #7aaae0 }
.pill-p3 { background: #2a1a30; color: #c890d0 }
.pill-mf { background: rgba(216,160,64,0.15); color: var(--warn-soft); border: 1px solid rgba(216,160,64,0.35) }
.lang-toggle { margin-left: auto }
.empty { color: var(--fg-faint); font-style: italic }
.sidepanel { margin-top: 16px; padding: 12px 16px; border: 1px solid var(--bd-strong); border-radius: 6px; background: var(--bg-card); display: flex; align-items: center; gap: 12px; flex-wrap: wrap }
.sidepanel a { color: var(--accent); text-decoration: none; font-weight: 600 }
.sidepanel a:hover { text-decoration: underline }
.sidepanel .note { color: var(--fg-dim); font-size: 11.5px; flex: 1; min-width: 240px }

@media (max-width: 600px) {
  .rt thead { display: none }
  .rt, .rt tbody, .rt tr, .rt td { display: block; width: 100% }
  .rt tr { border: 1px solid #1a2333; border-radius: 6px; padding: 10px 12px; margin-bottom: 8px; background: #0a1018 }
  .rt td { display: flex; justify-content: space-between; align-items: baseline; border: none; padding: 3px 0; gap: 10px; font-size: 12px }
  .rt td::before {
    content: attr(data-label);
    color: #5a7090; font-size: 10px; text-transform: uppercase; letter-spacing: .4px;
    font-family: var(--sans); font-weight: 600; flex-shrink: 0
  }
  .rt td.sys { justify-content: flex-start; font-size: 14px }
  .rt td.sys::before { display: none }
}
</style>
</head>
<body>

<header>
  <h1 data-i18n="title"></h1>
  <div class="crumb"><a href="index.html" data-i18n="back_db"></a></div>
  <div class="seg lang-toggle" id="lang-seg">
    <button class="on" data-lang="ko">한</button>
    <button data-lang="en">EN</button>
  </div>
</header>

<main>
<section>
  <h2 data-i18n="section_title"></h2>
  <div class="card">
    <p class="intro" data-i18n="intro"></p>
  </div>
  <div class="card">
    <table class="rt">
      <thead><tr>
        <th data-i18n="th_system"></th>
        <th data-i18n="th_phase2"></th>
        <th data-i18n="th_phase3"></th>
      </tr></thead>
      <tbody>
__ROWS__
      </tbody>
    </table>
  </div>
__SIDEPANELS__
</section>
</main>

<footer>
  <span data-i18n="footer_note"></span>
</footer>

<script>
const T = {
  en: {
    title: "NearStars · Reports",
    back_db: "← Back to database",
    section_title: "Curation reports",
    intro: "Per-system Phase 2 (paper-by-paper measurements) and per-planet Phase 3 (in-game representation synthesis) reports. Autogenerated when the curation work is committed; this page is regenerated by scripts/pipeline/build_reports_index.py.",
    th_system: "System",
    th_phase2: "Phase 2 (per host)",
    th_phase3: "Phase 3 (per planet)",
    footer_note: "NearStars · Reports index · autogenerated from docs/phase2/ and docs/phase3/",
    none: "—",
    mf_link: "Manual paper fetch index",
    mf_note: "Papers Phase 3 couldn't auto-fetch (no arXiv preprint) — paste the abstract back in to refine the synthesis."
  },
  ko: {
    title: "NearStars · 보고서",
    back_db: "← 데이터베이스로",
    section_title: "큐레이션 보고서",
    intro: "시스템별 Phase 2 (논문별 측정값) · 행성별 Phase 3 (인게임 표현 합성) 보고서. 큐레이션 작업이 커밋되면 자동 생성되며, 이 페이지는 scripts/pipeline/build_reports_index.py 가 재생성합니다.",
    th_system: "시스템",
    th_phase2: "Phase 2 (호스트별)",
    th_phase3: "Phase 3 (행성별)",
    footer_note: "NearStars · 보고서 인덱스 · docs/phase2/ + docs/phase3/ 에서 자동 생성",
    none: "—",
    mf_link: "수동 fetch 논문 인덱스",
    mf_note: "Phase 3 가 자동으로 가져오지 못한 논문들 (arXiv preprint 없음). abstract 를 다시 붙여 넣으면 합성을 갱신할 수 있습니다."
  }
};

let lang = localStorage.getItem('nearstars-lang') || 'ko';

function applyLang() {
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const v = T[lang][el.dataset.i18n];
    if (v !== undefined) el.innerHTML = v;
  });
  document.querySelectorAll('#lang-seg button').forEach(b => {
    b.classList.toggle('on', b.dataset.lang === lang);
  });
}

document.getElementById('lang-seg').addEventListener('click', e => {
  const btn = e.target.closest('button[data-lang]');
  if (!btn) return;
  lang = btn.dataset.lang;
  localStorage.setItem('nearstars-lang', lang);
  applyLang();
});

applyLang();
</script>

</body>
</html>
'''


def render_html(manifest: dict, has_manual_fetch: bool) -> str:
    if not manifest:
        rows = '<tr><td colspan="3" class="empty">No reports yet.</td></tr>'
    else:
        row_parts = []
        for host_name, info in sorted(manifest.items()):
            p2_cell = (
                f'<a href="{info["phase2"]}"><span class="pill pill-p2">P2</span> view</a>'
                if info.get('phase2') else '<span class="empty">—</span>'
            )
            p3_letters = info.get('phase3', {})
            if p3_letters:
                links = []
                for letter, path in sorted(p3_letters.items()):
                    links.append(f'<a href="{path}"><span class="pill pill-p3">P3</span> {letter}</a>')
                p3_cell = ' &nbsp; '.join(links)
            else:
                p3_cell = '<span class="empty">—</span>'
            row_parts.append(
                f'        <tr>\n'
                f'          <td class="sys" data-label="System">{host_name}</td>\n'
                f'          <td data-label="Phase 2">{p2_cell}</td>\n'
                f'          <td data-label="Phase 3">{p3_cell}</td>\n'
                f'        </tr>'
            )
        rows = '\n'.join(row_parts)

    sidepanels = ''
    if has_manual_fetch:
        sidepanels = (
            '  <div class="sidepanel">\n'
            '    <span class="pill pill-mf">MF</span>\n'
            '    <a href="phase3/manual-fetch.html" data-i18n="mf_link"></a>\n'
            '    <span class="note" data-i18n="mf_note"></span>\n'
            '  </div>'
        )

    return PAGE_TEMPLATE.replace('__ROWS__', rows).replace('__SIDEPANELS__', sidepanels)


def main() -> int:
    here = Path(__file__).resolve()
    repo = here.parent.parent.parent

    host_names, planet_map = load_db_names(repo)
    phase2_slugs, phase3_slugs = scan_reports(repo)
    manifest = build_manifest(host_names, planet_map, phase2_slugs, phase3_slugs)

    has_manual_fetch = (repo / 'docs' / 'phase3' / 'manual-fetch.html').exists()

    out_html = repo / 'docs' / 'reports.html'
    out_html.write_text(render_html(manifest, has_manual_fetch), encoding='utf-8')

    out_json = repo / 'docs' / 'reports-manifest.json'
    out_json.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding='utf-8')

    print(f'wrote {out_html.relative_to(repo)}')
    print(f'wrote {out_json.relative_to(repo)}')
    print(f'hosts: {len(manifest)}  '
          f'p2 reports: {sum(1 for v in manifest.values() if v.get("phase2"))}  '
          f'p3 reports: {sum(len(v.get("phase3", {})) for v in manifest.values())}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
