#!/bin/sh
# 위키 자동 ingest 훅 — git pre-commit 시 staged .md를 위키에 통합
# Generated by .agents/skills/llm-wiki/ (Phase 3 automation)

# Behavior:
#   1. Find staged .md files (added or modified).
#   2. Filter out raw tier + wiki state pages (don't re-ingest themselves).
#   3. Invoke `claude -p` headlessly to run `/wiki-ingest` on each.
#   4. Re-stage modified files (frontmatter + Related additions + wiki state).
#   5. On failure (no claude CLI, network down, etc.) — log + WARN but DON'T block commit.
#
# Failure is non-blocking by design. Drift can be caught later by weekly lint
# or manual `/wiki-refresh`. Better to ship the commit than to halt the user.

set +e  # don't abort on hook failure

REPO_ROOT="$(git rev-parse --show-toplevel)"
LOG="$REPO_ROOT/.wiki-hook.log"

# Collect staged .md files (added or modified)
STAGED_MDS=$(git diff --cached --name-only --diff-filter=AM | grep -E '\.md$' || true)
if [ -z "$STAGED_MDS" ]; then
  exit 0
fi

# Whitelist: only files in known wiki-tier directories get ingested.
# (Blacklist would catch unrelated .md edits like slash command defs,
# scripts/, README at root, etc., which don't belong in the wiki.)
is_wiki_path() {
  case "$1" in
    docs/reference/*.md) return 0 ;;
    docs/phase3/_papers/*|docs/phase3/_bib/*) return 1 ;;
    docs/phase3/*.md) return 0 ;;
    docs/wiki/*.md) return 1 ;;
    plans/_template.md|plans/README.md) return 1 ;;
    plans/*.md) return 0 ;;
    phase2/*/*.md|phase3/*/*.md) return 0 ;;
    docs/phase1-50ly/*.md|docs/famous-20-non-hosts/*.md) return 0 ;;
    *) return 1 ;;
  esac
}

WIKI_MDS=""
for f in $STAGED_MDS; do
  if is_wiki_path "$f"; then
    WIKI_MDS="$WIKI_MDS $f"
  fi
done

if [ -z "$WIKI_MDS" ]; then
  exit 0
fi

# Best-effort: bail gracefully if Claude CLI not available
if ! command -v claude >/dev/null 2>&1; then
  {
    echo ""
    echo "[$(date -Iseconds)] wiki-hook: claude CLI not found in PATH"
    echo "  staged but NOT ingested: $WIKI_MDS"
    echo "  run \`/wiki-ingest\` manually in your next Claude session"
  } >> "$LOG"
  echo "wiki-hook: claude CLI not in PATH — skipping auto-ingest (logged to .wiki-hook.log)" >&2
  exit 0
fi

# Invoke headless ingest
PROMPT="Run /wiki-ingest for the following files (space-separated):${WIKI_MDS}. Be silent about progress; output 'INGEST_OK <count>' on success, 'INGEST_FAIL <reason>' on error."

echo "wiki-hook: ingesting$WIKI_MDS" >&2
RESULT=$(claude -p "$PROMPT" 2>&1)
RC=$?

{
  echo ""
  echo "[$(date -Iseconds)] wiki-hook: ingest run"
  echo "  files:$WIKI_MDS"
  echo "  exit: $RC"
  echo "  output: $(echo "$RESULT" | head -5)"
} >> "$LOG"

if [ "$RC" -eq 0 ] && echo "$RESULT" | grep -q "INGEST_OK"; then
  # Re-stage modified files + wiki state pages
  for f in $WIKI_MDS; do
    git add "$f"
  done
  git add docs/wiki/index.md docs/wiki/log.md docs/wiki/hot.md 2>/dev/null || true
  echo "wiki-hook: ingest OK, re-staged wiki state" >&2
else
  echo "wiki-hook: ingest failed or skipped (logged to .wiki-hook.log) — commit proceeds anyway" >&2
fi

exit 0
