#!/usr/bin/env python3
# docs/ 발행 페이지의 사이트맵 + 연결성 감사를 생성 (고아·막다른 페이지·용량·CDN 의존)
"""Site map + connectivity audit for the published docs/ surface.

Walks every published `.html` under `docs/` (the gitignored `phase3/_papers/`
cache is excluded), builds the internal link graph, and writes
`docs/reference/site-map.md` + its ko mirror.

Reported per section: page count, total weight, the hub that reaches it, and
three defect classes:

  * **orphan** — no other published page links to it (unreachable by clicking)
  * **dead end** — links to no other published page
  * **CDN dependency** — needs the network to render as designed

Link extraction is static `href="…​.html"`, so a page whose links are built at
runtime from JSON (the DB browser `index.html` templates its rows from
`reports-manifest.json`) shows fewer outbound links than it really has; those
are annotated rather than guessed at.

Usage: python3 scripts/build_sitemap.py [--audit-only]
Exit code 1 with --audit-only if a NEW defect appears (see BASELINE below).
"""
from __future__ import annotations

import collections
import datetime
import glob
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(REPO, "docs")
EXCLUDE = ("phase3/_papers/",)

# Defects the owner has seen and accepted (or that are pending a separate task).
# A defect outside this set fails --audit-only, so a regression is loud.
BASELINE_ORPHANS = set()  # 2026-08-07 site-optimization pass 이후 고아 0 — 유지할 것

SECTIONS = [
    ("root", "Top-level surfaces", lambda p: "/" not in p),
    ("wiki", "Rendered reference docs + plans", lambda p: p.startswith("wiki/")),
    ("phase2", "Per-host measurement reports", lambda p: p.startswith("phase2/")),
    ("phase3", "Per-planet synthesis reports", lambda p: p.startswith("phase3/")),
    ("phase4", "Decision boards + orbit viewers", lambda p: p.startswith("phase4/")),
]


def published_pages():
    out = []
    for p in glob.glob(os.path.join(DOCS, "**", "*.html"), recursive=True):
        rel = os.path.relpath(p, DOCS)
        if any(x in rel.replace(os.sep, "/") for x in EXCLUDE):
            continue
        out.append(rel.replace(os.sep, "/"))
    return sorted(out)


def analyze(pages):
    known = set(pages)
    inbound = collections.Counter()
    outbound = {}
    cdn = collections.defaultdict(set)
    weight = {}
    for p in pages:
        full = os.path.join(DOCS, p)
        weight[p] = os.path.getsize(full)
        h = open(full, errors="ignore").read()
        outs = set()
        for href in set(re.findall(r'href="([^"#?]+\.html)[^"]*"', h)):
            tgt = os.path.normpath(os.path.join(os.path.dirname(p), href))
            tgt = tgt.replace(os.sep, "/")
            if tgt in known:
                outs.add(tgt)
                inbound[tgt] += 1
        outbound[p] = outs
        for host in set(re.findall(r'(?:src|href)="https://([a-z0-9.-]+)/', h)):
            if host in ("fonts.googleapis.com", "fonts.gstatic.com", "cdn.jsdelivr.net"):
                cdn[host].add(p)
    return inbound, outbound, cdn, weight


def mb(n):
    return f"{n / 1024 / 1024:.1f} MB"


def section_of(p):
    for key, _, test in SECTIONS:
        if test(p):
            return key
    return "other"


def build_report(pages, inbound, outbound, cdn, weight, ko=False):
    L = []
    add = L.append
    by_sec = collections.defaultdict(list)
    for p in pages:
        by_sec[section_of(p)].append(p)
    orphans = [p for p in pages if inbound[p] == 0]
    deadends = [p for p in pages if not outbound[p]]
    total = sum(weight.values())

    if ko:
        add("<!-- docs/ 발행 페이지 사이트맵 + 연결성 감사 (build_sitemap.py 자동 생성) -->")
        add("# 사이트맵: 발행 문서 표면")
        add("")
        add("> `python3 scripts/build_sitemap.py`로 생성. 손으로 고치지 말 것.")
        add(f"> 페이지 {len(pages)}개, 합계 {mb(total)}, 내부 링크 "
            f"{sum(len(v) for v in outbound.values())}개.")
        add("> gitignore된 논문 캐시(`docs/phase3/_papers/`)는 사이트가 아니라 로컬 캐시라 제외한다.")
        heads = ("구획", "페이지", "용량", "역할")
        t_struct, t_defect, t_cdn = "## 구조", "## 결함", "## CDN 의존"
    else:
        add("<!-- docs/ 발행 페이지 사이트맵 + 연결성 감사 (build_sitemap.py 자동 생성) -->")
        add("# Site map: the published doc surface")
        add("")
        add("> Generated by `python3 scripts/build_sitemap.py`. Do not hand-edit.")
        add(f"> {len(pages)} pages, {mb(total)} total, "
            f"{sum(len(v) for v in outbound.values())} internal links.")
        add("> The gitignored paper cache (`docs/phase3/_papers/`) is a local cache, not "
            "part of the site, and is excluded.")
        heads = ("Section", "Pages", "Weight", "Role")
        t_struct, t_defect, t_cdn = "## Structure", "## Defects", "## CDN dependencies"

    add("")
    add(t_struct)
    add("")
    add(f"| {heads[0]} | {heads[1]} | {heads[2]} | {heads[3]} |")
    add("|---|---:|---:|---|")
    for key, role, _ in SECTIONS:
        ps = by_sec.get(key, [])
        if not ps:
            continue
        w = sum(weight[p] for p in ps)
        add(f"| `{key}` | {len(ps)} | {mb(w)} | {role} |")
    add("")

    # hub listing: pages with the most outbound links
    hubs = sorted(outbound.items(), key=lambda kv: -len(kv[1]))[:6]
    add("**Hubs** (most outbound links):" if not ko else "**허브**(아웃바운드 링크 최다):")
    for p, o in hubs:
        add(f"- `{p}` → {len(o)}")
    add("")
    if ko:
        add("주의: `index.html`은 목록을 `reports-manifest.json`에서 런타임에 만들기 때문에 "
            "정적 href가 거의 없다. 실제로는 phase2/phase3 리포트 전부로 이어지는 최대 허브다. "
            "위키 페이지들이 61개씩 갖는 아웃바운드는 페이지마다 실린 전체 사이드바다.")
    else:
        add("Note: `index.html` builds its rows at runtime from `reports-manifest.json`, so it "
            "has almost no static hrefs; in practice it is the widest hub, reaching every "
            "phase2/phase3 report. The 61 outbound links on each wiki page are the full "
            "sidebar carried on every page.")
    add("")

    add(t_defect)
    add("")
    lbl_o = "고아 페이지 (인바운드 0, 클릭으로 도달 불가)" if ko else \
            "Orphans (zero inbound links, unreachable by clicking)"
    add(f"**{lbl_o}: {len(orphans)}**")
    add("")
    for p in orphans:
        mark = "" if p in BASELINE_ORPHANS else (" ← **신규**" if ko else " ← **NEW**")
        add(f"- `{p}`{mark}")
    add("")
    lbl_d = "막다른 페이지 (아웃바운드 0, 되돌아갈 링크 없음)" if ko else \
            "Dead ends (zero outbound links, no way back)"
    add(f"**{lbl_d}: {len(deadends)}**")
    add("")
    for p in deadends:
        add(f"- `{p}`")
    add("")

    add(t_cdn)
    add("")
    if ko:
        add("네트워크가 없으면 설계대로 렌더되지 않는 페이지들이다.")
    else:
        add("These pages do not render as designed without network access.")
    add("")
    for host, ps in sorted(cdn.items(), key=lambda kv: -len(kv[1])):
        add(f"- `{host}` — {len(ps)}" + (" 페이지" if ko else " pages"))
    add("")

    heaviest = sorted(weight.items(), key=lambda kv: -kv[1])[:8]
    add("## 최대 용량 페이지" if ko else "## Heaviest pages")
    add("")
    for p, w in heaviest:
        add(f"- `{p}` — {w // 1024} KB")
    add("")
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    add(f"<!-- generated {stamp} -->")
    return "\n".join(L) + "\n"


def main(argv):
    audit_only = "--audit-only" in argv
    pages = published_pages()
    inbound, outbound, cdn, weight = analyze(pages)
    orphans = {p for p in pages if inbound[p] == 0}
    new = orphans - BASELINE_ORPHANS
    if not audit_only:
        for ko, path in ((False, "docs/reference/site-map.md"),
                         (True, "ko/docs/reference/site-map.md")):
            out = os.path.join(REPO, path)
            open(out, "w").write(build_report(pages, inbound, outbound, cdn, weight, ko=ko))
            print(f"wrote {path}")
    print(f"pages: {len(pages)}  weight: {mb(sum(weight.values()))}  "
          f"orphans: {len(orphans)}  new-orphans: {len(new)}")
    if new:
        print("NEW ORPHANS: " + ", ".join(sorted(new)))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
