# 분자별 LTE 플라스마 발광색을 온도별로 엔진으로 산출 (뷰어 온도 슬라이더의 분자 패널 입력)
"""Compute per-molecule LTE plasma color vs temperature — the molecular analog
of element_temperature_colors.yaml, for the viewer's temperature slider.

Each panel molecule (from molecular_plasma_colors.yaml) is run as a single-species
composition (FORMULA:1.0) through the saha_boltzmann engine over a 1000-15000K
grid. The march is computed: low-T molecular bands (dissociation equilibrium) →
atomic lines → ionization. Same model + caveats as plasma_temperature_colors.yaml
(see plasma-color-methodology-review.md).

Molecules whose atoms are outside the engine's set (H/He/C/N/O/S/Mg/Ti/V/Fe) drop
those atoms (Cl, F, Si, ...) and color from the supported remainder — recorded in
`dropped` so the viewer can flag it. This is honest: we model what we have data for.

    python3 scripts/refs/build_molecular_temperature_colors.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import cie_color                                   # noqa: E402
import saha_boltzmann as sb                        # noqa: E402
from emit_atmosphere_color import composition_to_atoms, select_bands, TEMPS  # noqa: E402

SRC = ROOT / "db" / "refs" / "molecular_plasma_colors.yaml"
OUT = ROOT / "db" / "refs" / "molecular_temperature_colors.yaml"

HEADER = """\
# AUTO-GENERATED by scripts/refs/build_molecular_temperature_colors.py — do not edit.
# Per-molecule LTE plasma color vs temperature (1000-15000K, 1000K steps).
# Each molecule run as a single-species composition through the Saha-Boltzmann
# engine: molecular bands (dissociation equilibrium) -> atomic lines -> ionization.
# Model + caveats identical to plasma_temperature_colors.yaml (see
# plasma-color-methodology-review.md). Molecules with atoms outside the engine set
# (H/He/C/N/O/S/Mg/Ti/V/Fe) drop those atoms (see `dropped`) and color from the
# supported remainder. hex/rgb are the same color (rgb derived from the sRGB tuple).
"""


class NoAliasDumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def dominant(diag: dict) -> str:
    if diag["emission_fraction"] < 0.10:
        return "thermal"
    if diag["molecular_fraction"] >= 0.20:
        return "molecular bands"
    if diag["ionization_fraction"] >= 0.20:
        return "ionic"
    return "atomic lines"


def build() -> dict:
    src = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    mols = src.get("molecules", src)
    atomic, mol_db = sb.load_dbs()

    out: dict = {"molecules": {}}
    for formula, m in mols.items():
        elems, dropped, _ = composition_to_atoms(f"{formula}:1.0")
        entry: dict = {"atoms": m.get("atoms"), "colors": {}}
        if dropped:
            entry["dropped"] = sorted(dropped)
        if not elems:
            entry["note"] = "no engine-supported emitting atoms"
            out["molecules"][formula] = entry
            continue
        bands = select_bands(elems, mol_db)
        if bands:
            entry["bands"] = bands
        for T in TEMPS:
            inten, diag = sb.slab_spectrum_custom(elems, bands, T, atomic, mol_db)
            srgb = cie_color.spectrum_to_srgb_hue(inten)
            rgb = [round(c * 255) for c in srgb]
            entry["colors"][T] = {
                "temp_k": T,
                "hex": "#%02x%02x%02x" % tuple(rgb),
                "rgb": rgb,
                "dominant": dominant(diag),
                "ionization_fraction": diag["ionization_fraction"],
                "molecular_fraction": diag["molecular_fraction"],
            }
        out["molecules"][formula] = entry
    return out


def render(data: dict) -> str:
    return HEADER + yaml.dump(data, Dumper=NoAliasDumper, sort_keys=False,
                              allow_unicode=True)


def main() -> int:
    data = build()
    OUT.write_text(render(data), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(data['molecules'])} molecules x "
          f"{len(TEMPS)} temps)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
