# db/refs/element_plasma_colors.yaml 에서 docs/reference/element-plasma-colors.md (영문 + ko 미러) 를 렌더
"""Generate the human-readable element plasma colors doc from the YAML DB.

Writes:
    docs/reference/element-plasma-colors.md       (English)
    ko/docs/reference/element-plasma-colors.md    (Korean mirror)

Layout: header + status legend + per-period tables. Each row shows
symbol, name, status, hex (with color swatch in inline HTML
`<span style="background:#hex">` for browsers), basis snippet.

Run after editing the YAML DB. Idempotent.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
DB_PATH = ROOT / "db" / "refs" / "element_plasma_colors.yaml"
EN_OUT = ROOT / "docs" / "reference" / "element-plasma-colors.md"
KO_OUT = ROOT / "ko" / "docs" / "reference" / "element-plasma-colors.md"


PERIOD_BOUNDS = [
    (1, "Period 1", (1, 2)),
    (2, "Period 2", (3, 10)),
    (3, "Period 3", (11, 18)),
    (4, "Period 4", (19, 36)),
    (5, "Period 5", (37, 54)),
    (6, "Period 6 (main + transition)", (55, 56, 72, 86)),   # Cs, Ba, then Hf..Rn skipping La..Lu
    (7, "Lanthanides", (57, 71)),
    (8, "Period 7 (main + transition)", (87, 88, 104, 118)), # Fr, Ra, then Rf..Og skipping Ac..Lr
    (9, "Actinides", (89, 103)),
]


def select_period_entries(data, period_idx, bounds):
    """Return entries whose atomic_number falls in the period range(s)."""
    if len(bounds) == 2:
        lo, hi = bounds
        return [(s, e) for s, e in data.items()
                if lo <= e["atomic_number"] <= hi]
    elif len(bounds) == 4:
        a, b, c, d = bounds
        return [(s, e) for s, e in data.items()
                if a <= e["atomic_number"] <= b or c <= e["atomic_number"] <= d]
    return []


def status_chip_en(status: str) -> str:
    return {
        "visible":              "visible",
        "no_flame_color":       "no flame color",
        "not_visible_to_humans": "not visible to humans",
        "too_radioactive":      "too radioactive",
        "too_short":            "half-life too short",
        "no_data":              "no published data",
    }[status]


def status_chip_ko(status: str) -> str:
    return {
        "visible":              "관측 가능",
        "no_flame_color":       "불꽃색 없음",
        "not_visible_to_humans": "가시광선 밖",
        "too_radioactive":      "방사능 위험",
        "too_short":            "반감기 부족",
        "no_data":              "자료 없음",
    }[status]


def swatch_cell(hex_val: str | None) -> str:
    if hex_val is None:
        return "—"
    return (f'<span style="display:inline-block;width:1em;height:1em;'
            f'background:{hex_val};border:1px solid #444;vertical-align:middle"></span> '
            f'`{hex_val}`')


def render_table(entries, status_chip):
    lines = ["| Z | Sym | Name | Color | Status | Basis |",
             "|---|-----|------|-------|--------|-------|"]
    entries.sort(key=lambda x: x[1]["atomic_number"])
    for sym, e in entries:
        lines.append(
            f"| {e['atomic_number']} "
            f"| **{sym}** "
            f"| {e['name']} "
            f"| {swatch_cell(e.get('hex'))} "
            f"| {status_chip(e['status'])} "
            f"| {e['basis']} |"
        )
    return "\n".join(lines)


def render_en(data) -> str:
    lines = [
        "# Element plasma colors",
        "",
        "Per-element flame test / low-temperature plasma colors. "
        "Replaces pixel-sampling of the Helmenstine 2017 chart (whose "
        "decorative gradient blurs the intended hex). Source: chemistry "
        "literature + NIST Atomic Spectra Database, with the Helmenstine "
        "chart as visual sanity check.",
        "",
        "Canonical source: `db/refs/element_plasma_colors.yaml`. "
        "This file is generated by `scripts/refs/render_element_colors_doc.py` — "
        "do not edit by hand.",
        "",
        "## Status legend",
        "",
        "| Status | Meaning | Hex |",
        "|---|---|---|",
        "| visible | Documented flame/plasma emission color | required |",
        "| no flame color | Element exists but no visible flame coloration | null |",
        "| not visible to humans | Emission falls outside 380–780 nm | null |",
        "| too radioactive | Flame test unsafe / not characterized | null |",
        "| half-life too short | Synthetic, decays before observation | null |",
        "| no published data | Literature silent | null |",
        "",
        "Reentry plasma at 8,000–15,000 K differs from atomic flame "
        "emission — molecular bands (N2+, C2 Swan, CN violet) dominate. "
        "See [composition-color reference](../../.claude/skills/firefly-cfg/references/composition-color.md) "
        "for bulk-gas reentry colors used in Firefly cfg.",
        "",
    ]
    for _, title, bounds in PERIOD_BOUNDS:
        entries = select_period_entries(data, None, bounds)
        if not entries:
            continue
        lines.append(f"## {title}")
        lines.append("")
        lines.append(render_table(entries, status_chip_en))
        lines.append("")
    lines.append("## Related")
    lines.append("")
    lines.append("- [composition-color (firefly-cfg skill)](../../.claude/skills/firefly-cfg/references/composition-color.md) — bulk-gas reentry plasma palette (different physics regime)")
    lines.append("- [phase3-mapping (firefly-cfg skill)](../../.claude/skills/firefly-cfg/references/phase3-mapping.md) — Phase 3 → Firefly field map")
    lines.append("")
    return "\n".join(lines)


def render_ko(data) -> str:
    lines = [
        "# 원소별 플라즈마 색상",
        "",
        "주기율표 원소별 불꽃 반응 / 저온 플라즈마 색상 사전. Helmenstine 2017 "
        "차트(sciencenotes.org)는 장식용 그라디언트 때문에 정확한 hex 가 안 보여서, "
        "화학 문헌 + NIST 원자 스펙트럼 DB 를 1차 출처로 쓰고 차트는 시각 sanity "
        "check 로만 활용합니다.",
        "",
        "정본 데이터: `db/refs/element_plasma_colors.yaml`. 이 문서는 "
        "`scripts/refs/render_element_colors_doc.py` 가 자동 생성합니다 — "
        "직접 편집 금지.",
        "",
        "## 상태(status) 범례",
        "",
        "| 상태 | 의미 | Hex |",
        "|---|---|---|",
        "| 관측 가능 | 불꽃/플라즈마 색이 문헌에 기록됨 | 필수 |",
        "| 불꽃색 없음 | 원소 자체는 존재하나 가시 불꽃색이 없음 | null |",
        "| 가시광선 밖 | 방출선이 380–780 nm 밖에만 있음 | null |",
        "| 방사능 위험 | 불꽃 반응 자체가 안전상 불가 | null |",
        "| 반감기 부족 | 합성 원소, 관측 전 붕괴 | null |",
        "| 자료 없음 | 문헌이 침묵 | null |",
        "",
        "재진입 플라즈마(8,000–15,000 K)는 원자 불꽃 방출과 다릅니다 — 분자 "
        "밴드(N2+, C2 Swan, CN violet)가 우세합니다. Firefly cfg 의 "
        "bulk gas 색은 [composition-color reference](../../.claude/skills/firefly-cfg/references/composition-color.md) 를 참고하세요.",
        "",
    ]
    period_titles_ko = {
        "Period 1": "1주기",
        "Period 2": "2주기",
        "Period 3": "3주기",
        "Period 4": "4주기",
        "Period 5": "5주기",
        "Period 6 (main + transition)": "6주기 (주족 + 전이금속)",
        "Lanthanides": "란타넘족",
        "Period 7 (main + transition)": "7주기 (주족 + 전이금속)",
        "Actinides": "악티늄족",
    }
    for _, title, bounds in PERIOD_BOUNDS:
        entries = select_period_entries(data, None, bounds)
        if not entries:
            continue
        lines.append(f"## {period_titles_ko[title]}")
        lines.append("")
        lines.append(render_table(entries, status_chip_ko))
        lines.append("")
    lines.append("## Related")
    lines.append("")
    lines.append("- [composition-color (firefly-cfg 스킬)](../../.claude/skills/firefly-cfg/references/composition-color.md) — 재진입 plasma bulk gas 팔레트 (다른 물리 영역)")
    lines.append("- [phase3-mapping (firefly-cfg 스킬)](../../.claude/skills/firefly-cfg/references/phase3-mapping.md) — Phase 3 → Firefly 필드 매핑")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    with open(DB_PATH, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    EN_OUT.parent.mkdir(parents=True, exist_ok=True)
    KO_OUT.parent.mkdir(parents=True, exist_ok=True)
    EN_OUT.write_text(render_en(data), encoding="utf-8")
    KO_OUT.write_text(render_ko(data), encoding="utf-8")

    print(f"wrote {EN_OUT.relative_to(ROOT)}")
    print(f"wrote {KO_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
